import { statusCell, type DenseColumn } from '../grid/DenseDataGrid'
import type {
  Account,
  AccountActivity,
  AccountAddress,
  AccountRelationship,
  AuditLog,
  Contact,
  CustomerProfile,
  Department,
  LookupCategory,
  LookupValue,
  Permission,
  Role,
  SystemSetting,
  Team,
  User,
} from '../../types/models'

export type FieldKind = 'text' | 'textarea' | 'number' | 'checkbox' | 'select'

export type EntityField = {
  key: string
  label: string
  kind: FieldKind
  required?: boolean
  options?: Array<{ value: string; label: string }>
  readOnlyOnEdit?: boolean
}

export type FormState = Record<string, string | number | boolean>

export type EntityConfig<TItem extends { id: string }> = {
  key: string
  title: string
  subtitle: string
  endpoint: string
  permissions: { view: string; create?: string; update?: string; delete?: string }
  listPath: string
  createPath: string
  detailsPath: (id: string) => string
  editPath: (id: string) => string
  columns: DenseColumn<TItem>[]
  fields: EntityField[]
  defaultForm: FormState
  mapItemToForm: (item: TItem) => FormState
  mapCreatePayload: (form: FormState) => unknown
  mapUpdatePayload: (form: FormState, item: TItem) => unknown
  details: (item: TItem) => Array<{ label: string; value: string }>
  readOnly?: boolean
}

export const settingDataTypeOptions = [
  { value: '1', label: 'String' },
  { value: '2', label: 'Number' },
  { value: '3', label: 'Boolean' },
  { value: '4', label: 'Json' },
]

export const usersConfig: EntityConfig<User> = {
  key: 'users',
  title: 'Users',
  subtitle: 'Manage user accounts, lock status, and security assignments.',
  endpoint: 'api/users',
  permissions: { view: 'Users.View', create: 'Users.Create', update: 'Users.Update', delete: 'Users.Delete' },
  listPath: '/admin/users',
  createPath: '/admin/users/create',
  detailsPath: (id) => `/admin/users/${id}`,
  editPath: (id) => `/admin/users/${id}/edit`,
  columns: [
    { key: 'email', label: 'Email', sortable: true },
    { key: 'firstName', label: 'First Name', sortable: true },
    { key: 'lastName', label: 'Last Name', sortable: true },
    { key: 'isEnabled', label: 'Status', sortable: true, render: (row) => statusCell(row.isEnabled ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'email', label: 'Email', kind: 'text', required: true, readOnlyOnEdit: true },
    { key: 'password', label: 'Password', kind: 'text', required: true },
    { key: 'firstName', label: 'First Name', kind: 'text' },
    { key: 'lastName', label: 'Last Name', kind: 'text' },
    { key: 'isEnabled', label: 'Enabled', kind: 'checkbox' },
  ],
  defaultForm: { email: '', password: '', firstName: '', lastName: '', isEnabled: true },
  mapItemToForm: (item) => ({ email: item.email, password: '', firstName: item.firstName ?? '', lastName: item.lastName ?? '', isEnabled: item.isEnabled }),
  mapCreatePayload: (form) => ({
    email: String(form.email ?? ''),
    password: String(form.password ?? ''),
    firstName: String(form.firstName ?? ''),
    lastName: String(form.lastName ?? ''),
    isEnabled: Boolean(form.isEnabled),
  }),
  mapUpdatePayload: (form) => ({
    firstName: String(form.firstName ?? ''),
    lastName: String(form.lastName ?? ''),
    isEnabled: Boolean(form.isEnabled),
  }),
  details: (item) => [
    { label: 'Email', value: item.email },
    { label: 'First Name', value: item.firstName ?? '' },
    { label: 'Last Name', value: item.lastName ?? '' },
    { label: 'Enabled', value: item.isEnabled ? 'Yes' : 'No' },
    { label: 'Locked', value: item.isLocked ? 'Yes' : 'No' },
    { label: 'Roles', value: item.roles.join(', ') },
  ],
}

export const rolesConfig: EntityConfig<Role> = {
  key: 'roles',
  title: 'Roles',
  subtitle: 'Create and maintain role definitions.',
  endpoint: 'api/roles',
  permissions: { view: 'Roles.View', create: 'Roles.Create', update: 'Roles.Update', delete: 'Roles.Delete' },
  listPath: '/admin/roles',
  createPath: '/admin/roles/create',
  detailsPath: (id) => `/admin/roles/${id}`,
  editPath: (id) => `/admin/roles/${id}/edit`,
  columns: [
    { key: 'name', label: 'Name', sortable: true },
    { key: 'description', label: 'Description', sortable: true },
  ],
  fields: [
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
  ],
  defaultForm: { name: '', description: '' },
  mapItemToForm: (item) => ({ name: item.name, description: item.description ?? '' }),
  mapCreatePayload: (form) => ({ name: String(form.name ?? ''), description: String(form.description ?? '') || null }),
  mapUpdatePayload: (form) => ({ name: String(form.name ?? ''), description: String(form.description ?? '') || null }),
  details: (item) => [
    { label: 'Name', value: item.name },
    { label: 'Description', value: item.description ?? '' },
  ],
}

export const permissionsConfig: EntityConfig<Permission> = {
  key: 'permissions',
  title: 'Permissions',
  subtitle: 'Manage module/action permissions.',
  endpoint: 'api/permissions',
  permissions: { view: 'Roles.View', create: 'Roles.Create', update: 'Roles.Update', delete: 'Roles.Delete' },
  listPath: '/admin/permissions',
  createPath: '/admin/permissions/create',
  detailsPath: (id) => `/admin/permissions/${id}`,
  editPath: (id) => `/admin/permissions/${id}/edit`,
  columns: [
    { key: 'name', label: 'Permission', sortable: true },
    { key: 'module', label: 'Module', sortable: true },
    { key: 'action', label: 'Action', sortable: true },
  ],
  fields: [
    { key: 'module', label: 'Module', kind: 'text', required: true },
    { key: 'action', label: 'Action', kind: 'text', required: true },
  ],
  defaultForm: { module: '', action: '' },
  mapItemToForm: (item) => ({ module: item.module, action: item.action }),
  mapCreatePayload: (form) => ({ module: String(form.module ?? ''), action: String(form.action ?? '') }),
  mapUpdatePayload: (form) => ({ module: String(form.module ?? ''), action: String(form.action ?? '') }),
  details: (item) => [
    { label: 'Name', value: item.name },
    { label: 'Module', value: item.module },
    { label: 'Action', value: item.action },
  ],
}

export const teamsConfig: EntityConfig<Team> = {
  key: 'teams',
  title: 'Teams',
  subtitle: 'Configure team ownership and state.',
  endpoint: 'api/teams',
  permissions: { view: 'Teams.View', create: 'Teams.Create', update: 'Teams.Update', delete: 'Teams.Delete' },
  listPath: '/admin/teams',
  createPath: '/admin/teams/create',
  detailsPath: (id) => `/admin/teams/${id}`,
  editPath: (id) => `/admin/teams/${id}/edit`,
  columns: [
    { key: 'name', label: 'Name', sortable: true },
    { key: 'description', label: 'Description', sortable: true },
    { key: 'ownerUserId', label: 'Owner User Id', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'ownerUserId', label: 'Owner User Id', kind: 'text' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: { name: '', description: '', ownerUserId: '', isActive: true },
  mapItemToForm: (item) => ({ name: item.name, description: item.description ?? '', ownerUserId: item.ownerUserId ?? '', isActive: item.isActive }),
  mapCreatePayload: (form) => ({
    name: String(form.name ?? ''),
    description: String(form.description ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => ({
    name: String(form.name ?? ''),
    description: String(form.description ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  details: (item) => [
    { label: 'Name', value: item.name },
    { label: 'Description', value: item.description ?? '' },
    { label: 'Owner User Id', value: item.ownerUserId ?? '' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const departmentsConfig: EntityConfig<Department> = {
  key: 'departments',
  title: 'Departments',
  subtitle: 'Maintain department hierarchy and status.',
  endpoint: 'api/departments',
  permissions: { view: 'Departments.View', create: 'Departments.Create', update: 'Departments.Update', delete: 'Departments.Delete' },
  listPath: '/admin/departments',
  createPath: '/admin/departments/create',
  detailsPath: (id) => `/admin/departments/${id}`,
  editPath: (id) => `/admin/departments/${id}/edit`,
  columns: [
    { key: 'name', label: 'Name', sortable: true },
    { key: 'description', label: 'Description', sortable: true },
    { key: 'parentDepartmentId', label: 'Parent Department Id', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'parentDepartmentId', label: 'Parent Department Id', kind: 'text' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: { name: '', description: '', parentDepartmentId: '', isActive: true },
  mapItemToForm: (item) => ({ name: item.name, description: item.description ?? '', parentDepartmentId: item.parentDepartmentId ?? '', isActive: item.isActive }),
  mapCreatePayload: (form) => ({
    name: String(form.name ?? ''),
    description: String(form.description ?? '') || null,
    parentDepartmentId: String(form.parentDepartmentId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => ({
    name: String(form.name ?? ''),
    description: String(form.description ?? '') || null,
    parentDepartmentId: String(form.parentDepartmentId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  details: (item) => [
    { label: 'Name', value: item.name },
    { label: 'Description', value: item.description ?? '' },
    { label: 'Parent Department Id', value: item.parentDepartmentId ?? '' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const settingsConfig: EntityConfig<SystemSetting> = {
  key: 'system-settings',
  title: 'System Settings',
  subtitle: 'Configure global key/value settings.',
  endpoint: 'api/system-settings',
  permissions: { view: 'Settings.View', create: 'Settings.Update', update: 'Settings.Update', delete: 'Settings.Update' },
  listPath: '/admin/system-settings',
  createPath: '/admin/system-settings/create',
  detailsPath: (id) => `/admin/system-settings/${id}`,
  editPath: (id) => `/admin/system-settings/${id}/edit`,
  columns: [
    { key: 'category', label: 'Category', sortable: true },
    { key: 'key', label: 'Key', sortable: true },
    { key: 'value', label: 'Value', sortable: true },
    { key: 'dataType', label: 'Data Type', sortable: true, render: (row) => settingDataTypeOptions.find((x) => Number(x.value) === row.dataType)?.label ?? String(row.dataType) },
  ],
  fields: [
    { key: 'category', label: 'Category', kind: 'text', required: true },
    { key: 'key', label: 'Key', kind: 'text', required: true },
    { key: 'value', label: 'Value', kind: 'textarea', required: true },
    { key: 'dataType', label: 'Data Type', kind: 'select', required: true, options: settingDataTypeOptions },
    { key: 'description', label: 'Description', kind: 'textarea' },
  ],
  defaultForm: { category: '', key: '', value: '', dataType: '1', description: '' },
  mapItemToForm: (item) => ({ category: item.category, key: item.key, value: item.value, dataType: String(item.dataType), description: item.description ?? '' }),
  mapCreatePayload: (form) => ({
    category: String(form.category ?? ''),
    key: String(form.key ?? ''),
    value: String(form.value ?? ''),
    dataType: Number(form.dataType ?? 1),
    description: String(form.description ?? '') || null,
  }),
  mapUpdatePayload: (form) => ({
    category: String(form.category ?? ''),
    key: String(form.key ?? ''),
    value: String(form.value ?? ''),
    dataType: Number(form.dataType ?? 1),
    description: String(form.description ?? '') || null,
  }),
  details: (item) => [
    { label: 'Category', value: item.category },
    { label: 'Key', value: item.key },
    { label: 'Value', value: item.value },
    { label: 'Data Type', value: settingDataTypeOptions.find((x) => Number(x.value) === item.dataType)?.label ?? String(item.dataType) },
    { label: 'Description', value: item.description ?? '' },
  ],
}

export const lookupCategoriesConfig: EntityConfig<LookupCategory> = {
  key: 'lookup-categories',
  title: 'Lookup Categories',
  subtitle: 'Manage reference data categories.',
  endpoint: 'api/lookup-categories',
  permissions: { view: 'ReferenceData.View', create: 'ReferenceData.Create', update: 'ReferenceData.Update', delete: 'ReferenceData.Delete' },
  listPath: '/admin/lookup-categories',
  createPath: '/admin/lookup-categories/create',
  detailsPath: (id) => `/admin/lookup-categories/${id}`,
  editPath: (id) => `/admin/lookup-categories/${id}/edit`,
  columns: [
    { key: 'name', label: 'Name', sortable: true },
    { key: 'code', label: 'Code', sortable: true },
    { key: 'description', label: 'Description', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'code', label: 'Code', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: { name: '', code: '', description: '', isActive: true },
  mapItemToForm: (item) => ({ name: item.name, code: item.code, description: item.description ?? '', isActive: item.isActive }),
  mapCreatePayload: (form) => ({ name: String(form.name ?? ''), code: String(form.code ?? ''), description: String(form.description ?? '') || null, isActive: Boolean(form.isActive) }),
  mapUpdatePayload: (form) => ({ name: String(form.name ?? ''), code: String(form.code ?? ''), description: String(form.description ?? '') || null, isActive: Boolean(form.isActive) }),
  details: (item) => [
    { label: 'Name', value: item.name },
    { label: 'Code', value: item.code },
    { label: 'Description', value: item.description ?? '' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const lookupValuesConfig: EntityConfig<LookupValue> = {
  key: 'lookup-values',
  title: 'Lookup Values',
  subtitle: 'Manage values and sort order in reference categories.',
  endpoint: 'api/lookup-values',
  permissions: { view: 'ReferenceData.View', create: 'ReferenceData.Create', update: 'ReferenceData.Update', delete: 'ReferenceData.Delete' },
  listPath: '/admin/lookup-values',
  createPath: '/admin/lookup-values/create',
  detailsPath: (id) => `/admin/lookup-values/${id}`,
  editPath: (id) => `/admin/lookup-values/${id}/edit`,
  columns: [
    { key: 'name', label: 'Name', sortable: true },
    { key: 'code', label: 'Code', sortable: true },
    { key: 'sortOrder', label: 'Sort', sortable: true },
    { key: 'isDefault', label: 'Default', sortable: true, render: (row) => statusCell(row.isDefault ? 'Default' : 'No') },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'lookupCategoryId', label: 'Lookup Category Id', kind: 'text', required: true },
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'code', label: 'Code', kind: 'text', required: true },
    { key: 'sortOrder', label: 'Sort Order', kind: 'number' },
    { key: 'isDefault', label: 'Default', kind: 'checkbox' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: { lookupCategoryId: '', name: '', code: '', sortOrder: 0, isDefault: false, isActive: true },
  mapItemToForm: (item) => ({ lookupCategoryId: item.lookupCategoryId, name: item.name, code: item.code, sortOrder: item.sortOrder, isDefault: item.isDefault, isActive: item.isActive }),
  mapCreatePayload: (form) => ({
    lookupCategoryId: String(form.lookupCategoryId ?? ''),
    name: String(form.name ?? ''),
    code: String(form.code ?? ''),
    sortOrder: Number(form.sortOrder ?? 0),
    isDefault: Boolean(form.isDefault),
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => ({
    lookupCategoryId: String(form.lookupCategoryId ?? ''),
    name: String(form.name ?? ''),
    code: String(form.code ?? ''),
    sortOrder: Number(form.sortOrder ?? 0),
    isDefault: Boolean(form.isDefault),
    isActive: Boolean(form.isActive),
  }),
  details: (item) => [
    { label: 'Lookup Category Id', value: item.lookupCategoryId },
    { label: 'Name', value: item.name },
    { label: 'Code', value: item.code },
    { label: 'Sort Order', value: String(item.sortOrder) },
    { label: 'Default', value: item.isDefault ? 'Yes' : 'No' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const auditLogsConfig: EntityConfig<AuditLog> = {
  key: 'audit-logs',
  title: 'Audit Logs',
  subtitle: 'Review immutable audit history records.',
  endpoint: 'api/audit-logs',
  permissions: { view: 'AuditLogs.View' },
  listPath: '/admin/audit-logs',
  createPath: '/admin/audit-logs/create',
  detailsPath: (id) => `/admin/audit-logs/${id}`,
  editPath: (id) => `/admin/audit-logs/${id}/edit`,
  columns: [
    { key: 'entityName', label: 'Entity', sortable: true },
    { key: 'entityId', label: 'Entity Id', sortable: true },
    { key: 'action', label: 'Action', sortable: true },
    { key: 'createdAt', label: 'Created At', sortable: true },
  ],
  fields: [],
  defaultForm: {},
  mapItemToForm: () => ({}),
  mapCreatePayload: () => ({}),
  mapUpdatePayload: () => ({}),
  details: (item) => [
    { label: 'Entity', value: item.entityName },
    { label: 'Entity Id', value: item.entityId },
    { label: 'Action', value: item.action },
    { label: 'Created At', value: item.createdAt },
    { label: 'User Id', value: item.userId ?? '' },
    { label: 'IP Address', value: item.ipAddress ?? '' },
    { label: 'User Agent', value: item.userAgent ?? '' },
    { label: 'Old Values', value: item.oldValues ?? '' },
    { label: 'New Values', value: item.newValues ?? '' },
  ],
  readOnly: true,
}

export const accountsConfig: EntityConfig<Account> = {
  key: 'accounts',
  title: 'Accounts',
  subtitle: 'Manage customer and organization accounts.',
  endpoint: 'api/accounts',
  permissions: { view: 'Accounts.View', create: 'Accounts.Create', update: 'Accounts.Update', delete: 'Accounts.Delete' },
  listPath: '/crm/accounts',
  createPath: '/crm/accounts/create',
  detailsPath: (id) => `/crm/accounts/${id}`,
  editPath: (id) => `/crm/accounts/${id}/edit`,
  columns: [
    { key: 'accountNumber', label: 'Account #', sortable: true },
    { key: 'name', label: 'Name', sortable: true },
    { key: 'email', label: 'Email', sortable: true },
    { key: 'mainPhone', label: 'Main Phone', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'accountNumber', label: 'Account Number', kind: 'text', required: true },
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'legalName', label: 'Legal Name', kind: 'text' },
    { key: 'tradingName', label: 'Trading Name', kind: 'text' },
    { key: 'accountTypeId', label: 'Account Type Lookup Id', kind: 'text' },
    { key: 'industryId', label: 'Industry Lookup Id', kind: 'text' },
    { key: 'ownershipTypeId', label: 'Ownership Type Lookup Id', kind: 'text' },
    { key: 'customerStatusId', label: 'Customer Status Lookup Id', kind: 'text' },
    { key: 'customerSegmentId', label: 'Customer Segment Lookup Id', kind: 'text' },
    { key: 'website', label: 'Website', kind: 'text' },
    { key: 'mainPhone', label: 'Main Phone', kind: 'text' },
    { key: 'alternatePhone', label: 'Alternate Phone', kind: 'text' },
    { key: 'email', label: 'Email', kind: 'text' },
    { key: 'fax', label: 'Fax', kind: 'text' },
    { key: 'taxNumber', label: 'Tax Number', kind: 'text' },
    { key: 'registrationNumber', label: 'Registration Number', kind: 'text' },
    { key: 'annualRevenue', label: 'Annual Revenue', kind: 'number' },
    { key: 'numberOfEmployees', label: 'Employees', kind: 'number' },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'parentAccountId', label: 'Parent Account Id', kind: 'text' },
    { key: 'primaryContactId', label: 'Primary Contact Id', kind: 'text' },
    { key: 'ownerUserId', label: 'Owner User Id', kind: 'text' },
    { key: 'ownerTeamId', label: 'Owner Team Id', kind: 'text' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: {
    accountNumber: '', name: '', legalName: '', tradingName: '', accountTypeId: '', industryId: '', ownershipTypeId: '', customerStatusId: '', customerSegmentId: '',
    website: '', mainPhone: '', alternatePhone: '', email: '', fax: '', taxNumber: '', registrationNumber: '', annualRevenue: 0, numberOfEmployees: 0,
    description: '', parentAccountId: '', primaryContactId: '', ownerUserId: '', ownerTeamId: '', isActive: true,
  },
  mapItemToForm: (item) => ({
    accountNumber: item.accountNumber, name: item.name, legalName: item.legalName ?? '', tradingName: item.tradingName ?? '', accountTypeId: item.accountTypeId ?? '',
    industryId: item.industryId ?? '', ownershipTypeId: item.ownershipTypeId ?? '', customerStatusId: item.customerStatusId ?? '', customerSegmentId: item.customerSegmentId ?? '',
    website: item.website ?? '', mainPhone: item.mainPhone ?? '', alternatePhone: item.alternatePhone ?? '', email: item.email ?? '', fax: item.fax ?? '', taxNumber: item.taxNumber ?? '',
    registrationNumber: item.registrationNumber ?? '', annualRevenue: item.annualRevenue ?? 0, numberOfEmployees: item.numberOfEmployees ?? 0,
    description: item.description ?? '', parentAccountId: item.parentAccountId ?? '', primaryContactId: item.primaryContactId ?? '', ownerUserId: item.ownerUserId ?? '', ownerTeamId: item.ownerTeamId ?? '', isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    accountNumber: String(form.accountNumber ?? ''),
    name: String(form.name ?? ''),
    legalName: String(form.legalName ?? '') || null,
    tradingName: String(form.tradingName ?? '') || null,
    accountTypeId: String(form.accountTypeId ?? '') || null,
    industryId: String(form.industryId ?? '') || null,
    ownershipTypeId: String(form.ownershipTypeId ?? '') || null,
    customerStatusId: String(form.customerStatusId ?? '') || null,
    customerSegmentId: String(form.customerSegmentId ?? '') || null,
    website: String(form.website ?? '') || null,
    mainPhone: String(form.mainPhone ?? '') || null,
    alternatePhone: String(form.alternatePhone ?? '') || null,
    email: String(form.email ?? '') || null,
    fax: String(form.fax ?? '') || null,
    taxNumber: String(form.taxNumber ?? '') || null,
    registrationNumber: String(form.registrationNumber ?? '') || null,
    annualRevenue: Number(form.annualRevenue ?? 0) || null,
    numberOfEmployees: Number(form.numberOfEmployees ?? 0) || null,
    description: String(form.description ?? '') || null,
    parentAccountId: String(form.parentAccountId ?? '') || null,
    primaryContactId: String(form.primaryContactId ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    ownerTeamId: String(form.ownerTeamId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => ({
    accountNumber: String(form.accountNumber ?? ''),
    name: String(form.name ?? ''),
    legalName: String(form.legalName ?? '') || null,
    tradingName: String(form.tradingName ?? '') || null,
    accountTypeId: String(form.accountTypeId ?? '') || null,
    industryId: String(form.industryId ?? '') || null,
    ownershipTypeId: String(form.ownershipTypeId ?? '') || null,
    customerStatusId: String(form.customerStatusId ?? '') || null,
    customerSegmentId: String(form.customerSegmentId ?? '') || null,
    website: String(form.website ?? '') || null,
    mainPhone: String(form.mainPhone ?? '') || null,
    alternatePhone: String(form.alternatePhone ?? '') || null,
    email: String(form.email ?? '') || null,
    fax: String(form.fax ?? '') || null,
    taxNumber: String(form.taxNumber ?? '') || null,
    registrationNumber: String(form.registrationNumber ?? '') || null,
    annualRevenue: Number(form.annualRevenue ?? 0) || null,
    numberOfEmployees: Number(form.numberOfEmployees ?? 0) || null,
    description: String(form.description ?? '') || null,
    parentAccountId: String(form.parentAccountId ?? '') || null,
    primaryContactId: String(form.primaryContactId ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    ownerTeamId: String(form.ownerTeamId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  details: (item) => [
    { label: 'Account Number', value: item.accountNumber },
    { label: 'Name', value: item.name },
    { label: 'Legal Name', value: item.legalName ?? '' },
    { label: 'Trading Name', value: item.tradingName ?? '' },
    { label: 'Email', value: item.email ?? '' },
    { label: 'Main Phone', value: item.mainPhone ?? '' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const contactsConfig: EntityConfig<Contact> = {
  key: 'contacts',
  title: 'Contacts',
  subtitle: 'Manage account contacts and communication preferences.',
  endpoint: 'api/contacts',
  permissions: { view: 'Contacts.View', create: 'Contacts.Create', update: 'Contacts.Update', delete: 'Contacts.Delete' },
  listPath: '/crm/contacts',
  createPath: '/crm/contacts/create',
  detailsPath: (id) => `/crm/contacts/${id}`,
  editPath: (id) => `/crm/contacts/${id}/edit`,
  columns: [
    { key: 'firstName', label: 'First Name', sortable: true },
    { key: 'lastName', label: 'Last Name', sortable: true },
    { key: 'email', label: 'Email', sortable: true },
    { key: 'jobTitle', label: 'Job Title', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'accountId', label: 'Account Id', kind: 'text', required: true },
    { key: 'contactRoleId', label: 'Contact Role Lookup Id', kind: 'text' },
    { key: 'salutationId', label: 'Salutation Lookup Id', kind: 'text' },
    { key: 'firstName', label: 'First Name', kind: 'text', required: true },
    { key: 'middleName', label: 'Middle Name', kind: 'text' },
    { key: 'lastName', label: 'Last Name', kind: 'text', required: true },
    { key: 'jobTitle', label: 'Job Title', kind: 'text' },
    { key: 'departmentName', label: 'Department', kind: 'text' },
    { key: 'email', label: 'Email', kind: 'text' },
    { key: 'mobilePhone', label: 'Mobile Phone', kind: 'text' },
    { key: 'workPhone', label: 'Work Phone', kind: 'text' },
    { key: 'extension', label: 'Extension', kind: 'text' },
    { key: 'preferredCommunicationId', label: 'Preferred Communication Lookup Id', kind: 'text' },
    { key: 'isPrimaryContact', label: 'Primary Contact', kind: 'checkbox' },
    { key: 'dateOfBirth', label: 'Date Of Birth (ISO)', kind: 'text' },
    { key: 'notes', label: 'Notes', kind: 'textarea' },
    { key: 'ownerUserId', label: 'Owner User Id', kind: 'text' },
    { key: 'ownerTeamId', label: 'Owner Team Id', kind: 'text' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: {
    accountId: '', contactRoleId: '', salutationId: '', firstName: '', middleName: '', lastName: '', jobTitle: '', departmentName: '', email: '', mobilePhone: '', workPhone: '', extension: '', preferredCommunicationId: '',
    isPrimaryContact: false, dateOfBirth: '', notes: '', ownerUserId: '', ownerTeamId: '', isActive: true,
  },
  mapItemToForm: (item) => ({
    accountId: item.accountId, contactRoleId: item.contactRoleId ?? '', salutationId: item.salutationId ?? '', firstName: item.firstName, middleName: item.middleName ?? '', lastName: item.lastName,
    jobTitle: item.jobTitle ?? '', departmentName: item.departmentName ?? '', email: item.email ?? '', mobilePhone: item.mobilePhone ?? '', workPhone: item.workPhone ?? '', extension: item.extension ?? '',
    preferredCommunicationId: item.preferredCommunicationId ?? '', isPrimaryContact: item.isPrimaryContact, dateOfBirth: item.dateOfBirth ?? '', notes: item.notes ?? '', ownerUserId: item.ownerUserId ?? '', ownerTeamId: item.ownerTeamId ?? '', isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    accountId: String(form.accountId ?? ''),
    contactRoleId: String(form.contactRoleId ?? '') || null,
    salutationId: String(form.salutationId ?? '') || null,
    firstName: String(form.firstName ?? ''),
    middleName: String(form.middleName ?? '') || null,
    lastName: String(form.lastName ?? ''),
    jobTitle: String(form.jobTitle ?? '') || null,
    departmentName: String(form.departmentName ?? '') || null,
    email: String(form.email ?? '') || null,
    mobilePhone: String(form.mobilePhone ?? '') || null,
    workPhone: String(form.workPhone ?? '') || null,
    extension: String(form.extension ?? '') || null,
    preferredCommunicationId: String(form.preferredCommunicationId ?? '') || null,
    isPrimaryContact: Boolean(form.isPrimaryContact),
    dateOfBirth: String(form.dateOfBirth ?? '') || null,
    notes: String(form.notes ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    ownerTeamId: String(form.ownerTeamId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form, item) => {
    const payload = contactsConfig.mapCreatePayload(form) as Record<string, unknown>
    return { ...payload, id: item.id }
  },
  details: (item) => [
    { label: 'Account Id', value: item.accountId },
    { label: 'Name', value: `${item.firstName} ${item.lastName}`.trim() },
    { label: 'Email', value: item.email ?? '' },
    { label: 'Mobile Phone', value: item.mobilePhone ?? '' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const accountAddressesConfig: EntityConfig<AccountAddress> = {
  key: 'account-addresses',
  title: 'Account Addresses',
  subtitle: 'Manage billing, shipping, and service addresses.',
  endpoint: 'api/account-addresses',
  permissions: { view: 'AccountAddresses.View', create: 'AccountAddresses.Create', update: 'AccountAddresses.Update', delete: 'AccountAddresses.Delete' },
  listPath: '/crm/account-addresses',
  createPath: '/crm/account-addresses/create',
  detailsPath: (id) => `/crm/account-addresses/${id}`,
  editPath: (id) => `/crm/account-addresses/${id}/edit`,
  columns: [
    { key: 'line1', label: 'Address Line 1', sortable: true },
    { key: 'city', label: 'City', sortable: true },
    { key: 'stateProvince', label: 'State/Province', sortable: true },
    { key: 'postalCode', label: 'Postal Code', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'accountId', label: 'Account Id', kind: 'text', required: true },
    { key: 'addressTypeId', label: 'Address Type Lookup Id', kind: 'text' },
    { key: 'attentionTo', label: 'Attention To', kind: 'text' },
    { key: 'line1', label: 'Line 1', kind: 'text', required: true },
    { key: 'line2', label: 'Line 2', kind: 'text' },
    { key: 'landmark', label: 'Landmark', kind: 'text' },
    { key: 'city', label: 'City', kind: 'text' },
    { key: 'stateProvince', label: 'State/Province', kind: 'text' },
    { key: 'postalCode', label: 'Postal Code', kind: 'text' },
    { key: 'countryId', label: 'Country Lookup Id', kind: 'text' },
    { key: 'latitude', label: 'Latitude', kind: 'number' },
    { key: 'longitude', label: 'Longitude', kind: 'number' },
    { key: 'isPrimary', label: 'Primary', kind: 'checkbox' },
    { key: 'isBilling', label: 'Billing', kind: 'checkbox' },
    { key: 'isShipping', label: 'Shipping', kind: 'checkbox' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: {
    accountId: '', addressTypeId: '', attentionTo: '', line1: '', line2: '', landmark: '', city: '', stateProvince: '', postalCode: '', countryId: '', latitude: 0, longitude: 0,
    isPrimary: false, isBilling: false, isShipping: false, isActive: true,
  },
  mapItemToForm: (item) => ({
    accountId: item.accountId, addressTypeId: item.addressTypeId ?? '', attentionTo: item.attentionTo ?? '', line1: item.line1, line2: item.line2 ?? '', landmark: item.landmark ?? '', city: item.city ?? '', stateProvince: item.stateProvince ?? '',
    postalCode: item.postalCode ?? '', countryId: item.countryId ?? '', latitude: item.latitude ?? 0, longitude: item.longitude ?? 0, isPrimary: item.isPrimary, isBilling: item.isBilling, isShipping: item.isShipping, isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    accountId: String(form.accountId ?? ''),
    addressTypeId: String(form.addressTypeId ?? '') || null,
    attentionTo: String(form.attentionTo ?? '') || null,
    line1: String(form.line1 ?? ''),
    line2: String(form.line2 ?? '') || null,
    landmark: String(form.landmark ?? '') || null,
    city: String(form.city ?? '') || null,
    stateProvince: String(form.stateProvince ?? '') || null,
    postalCode: String(form.postalCode ?? '') || null,
    countryId: String(form.countryId ?? '') || null,
    latitude: Number(form.latitude ?? 0) || null,
    longitude: Number(form.longitude ?? 0) || null,
    isPrimary: Boolean(form.isPrimary),
    isBilling: Boolean(form.isBilling),
    isShipping: Boolean(form.isShipping),
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form, item) => {
    const payload = accountAddressesConfig.mapCreatePayload(form) as Record<string, unknown>
    return { ...payload, id: item.id }
  },
  details: (item) => [
    { label: 'Account Id', value: item.accountId },
    { label: 'Address', value: `${item.line1}${item.city ? `, ${item.city}` : ''}` },
    { label: 'Postal Code', value: item.postalCode ?? '' },
    { label: 'Primary', value: item.isPrimary ? 'Yes' : 'No' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const customerProfilesConfig: EntityConfig<CustomerProfile> = {
  key: 'customer-profiles',
  title: 'Customer Profiles',
  subtitle: 'Manage customer financial and lifecycle profile attributes.',
  endpoint: 'api/customer-profiles',
  permissions: { view: 'CustomerProfiles.View', create: 'CustomerProfiles.Create', update: 'CustomerProfiles.Update', delete: 'CustomerProfiles.Delete' },
  listPath: '/crm/customer-profiles',
  createPath: '/crm/customer-profiles/create',
  detailsPath: (id) => `/crm/customer-profiles/${id}`,
  editPath: (id) => `/crm/customer-profiles/${id}/edit`,
  columns: [
    { key: 'accountId', label: 'Account Id', sortable: true },
    { key: 'creditLimit', label: 'Credit Limit', sortable: true },
    { key: 'customerSince', label: 'Customer Since', sortable: true },
  ],
  fields: [
    { key: 'accountId', label: 'Account Id', kind: 'text', required: true },
    { key: 'creditLimit', label: 'Credit Limit', kind: 'number' },
    { key: 'paymentTermsId', label: 'Payment Terms Lookup Id', kind: 'text' },
    { key: 'preferredCurrencyId', label: 'Preferred Currency Lookup Id', kind: 'text' },
    { key: 'preferredLanguageId', label: 'Preferred Language Lookup Id', kind: 'text' },
    { key: 'timeZoneId', label: 'Time Zone Lookup Id', kind: 'text' },
    { key: 'riskRatingId', label: 'Risk Rating Lookup Id', kind: 'text' },
    { key: 'lifecycleStageId', label: 'Lifecycle Stage Lookup Id', kind: 'text' },
    { key: 'customerSince', label: 'Customer Since (ISO)', kind: 'text' },
    { key: 'lastReviewDate', label: 'Last Review Date (ISO)', kind: 'text' },
    { key: 'nextReviewDate', label: 'Next Review Date (ISO)', kind: 'text' },
    { key: 'churnRiskScore', label: 'Churn Risk Score', kind: 'number' },
    { key: 'satisfactionScore', label: 'Satisfaction Score', kind: 'number' },
    { key: 'notes', label: 'Notes', kind: 'textarea' },
  ],
  defaultForm: {
    accountId: '', creditLimit: 0, paymentTermsId: '', preferredCurrencyId: '', preferredLanguageId: '', timeZoneId: '', riskRatingId: '', lifecycleStageId: '',
    customerSince: '', lastReviewDate: '', nextReviewDate: '', churnRiskScore: 0, satisfactionScore: 0, notes: '',
  },
  mapItemToForm: (item) => ({
    accountId: item.accountId, creditLimit: item.creditLimit ?? 0, paymentTermsId: item.paymentTermsId ?? '', preferredCurrencyId: item.preferredCurrencyId ?? '',
    preferredLanguageId: item.preferredLanguageId ?? '', timeZoneId: item.timeZoneId ?? '', riskRatingId: item.riskRatingId ?? '', lifecycleStageId: item.lifecycleStageId ?? '',
    customerSince: item.customerSince ?? '', lastReviewDate: item.lastReviewDate ?? '', nextReviewDate: item.nextReviewDate ?? '', churnRiskScore: item.churnRiskScore ?? 0, satisfactionScore: item.satisfactionScore ?? 0, notes: item.notes ?? '',
  }),
  mapCreatePayload: (form) => ({
    accountId: String(form.accountId ?? ''),
    creditLimit: Number(form.creditLimit ?? 0) || null,
    paymentTermsId: String(form.paymentTermsId ?? '') || null,
    preferredCurrencyId: String(form.preferredCurrencyId ?? '') || null,
    preferredLanguageId: String(form.preferredLanguageId ?? '') || null,
    timeZoneId: String(form.timeZoneId ?? '') || null,
    riskRatingId: String(form.riskRatingId ?? '') || null,
    lifecycleStageId: String(form.lifecycleStageId ?? '') || null,
    customerSince: String(form.customerSince ?? '') || null,
    lastReviewDate: String(form.lastReviewDate ?? '') || null,
    nextReviewDate: String(form.nextReviewDate ?? '') || null,
    churnRiskScore: Number(form.churnRiskScore ?? 0) || null,
    satisfactionScore: Number(form.satisfactionScore ?? 0) || null,
    notes: String(form.notes ?? '') || null,
  }),
  mapUpdatePayload: (form, item) => {
    const payload = customerProfilesConfig.mapCreatePayload(form) as Record<string, unknown>
    return { ...payload, id: item.id }
  },
  details: (item) => [
    { label: 'Account Id', value: item.accountId },
    { label: 'Credit Limit', value: String(item.creditLimit ?? '') },
    { label: 'Customer Since', value: item.customerSince ?? '' },
    { label: 'Notes', value: item.notes ?? '' },
  ],
}

export const accountRelationshipsConfig: EntityConfig<AccountRelationship> = {
  key: 'account-relationships',
  title: 'Account Relationships',
  subtitle: 'Track relationship links between accounts.',
  endpoint: 'api/account-relationships',
  permissions: { view: 'AccountRelationships.View', create: 'AccountRelationships.Create', update: 'AccountRelationships.Update', delete: 'AccountRelationships.Delete' },
  listPath: '/crm/account-relationships',
  createPath: '/crm/account-relationships/create',
  detailsPath: (id) => `/crm/account-relationships/${id}`,
  editPath: (id) => `/crm/account-relationships/${id}/edit`,
  columns: [
    { key: 'sourceAccountId', label: 'Source Account', sortable: true },
    { key: 'targetAccountId', label: 'Target Account', sortable: true },
    { key: 'relationshipTypeId', label: 'Type Lookup Id', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'sourceAccountId', label: 'Source Account Id', kind: 'text', required: true },
    { key: 'targetAccountId', label: 'Target Account Id', kind: 'text', required: true },
    { key: 'relationshipTypeId', label: 'Relationship Type Lookup Id', kind: 'text' },
    { key: 'startDate', label: 'Start Date (ISO)', kind: 'text' },
    { key: 'endDate', label: 'End Date (ISO)', kind: 'text' },
    { key: 'strengthId', label: 'Strength Lookup Id', kind: 'text' },
    { key: 'notes', label: 'Notes', kind: 'textarea' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: { sourceAccountId: '', targetAccountId: '', relationshipTypeId: '', startDate: '', endDate: '', strengthId: '', notes: '', isActive: true },
  mapItemToForm: (item) => ({
    sourceAccountId: item.sourceAccountId,
    targetAccountId: item.targetAccountId,
    relationshipTypeId: item.relationshipTypeId ?? '',
    startDate: item.startDate ?? '',
    endDate: item.endDate ?? '',
    strengthId: item.strengthId ?? '',
    notes: item.notes ?? '',
    isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    sourceAccountId: String(form.sourceAccountId ?? ''),
    targetAccountId: String(form.targetAccountId ?? ''),
    relationshipTypeId: String(form.relationshipTypeId ?? '') || null,
    startDate: String(form.startDate ?? '') || null,
    endDate: String(form.endDate ?? '') || null,
    strengthId: String(form.strengthId ?? '') || null,
    notes: String(form.notes ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form, item) => {
    const payload = accountRelationshipsConfig.mapCreatePayload(form) as Record<string, unknown>
    return { ...payload, id: item.id }
  },
  details: (item) => [
    { label: 'Source Account Id', value: item.sourceAccountId },
    { label: 'Target Account Id', value: item.targetAccountId },
    { label: 'Relationship Type', value: item.relationshipTypeId ?? '' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const accountActivitiesConfig: EntityConfig<AccountActivity> = {
  key: 'account-activities',
  title: 'Account Activities',
  subtitle: 'Track interactions and follow-up actions for accounts.',
  endpoint: 'api/account-activities',
  permissions: { view: 'AccountActivities.View', create: 'AccountActivities.Create', update: 'AccountActivities.Update', delete: 'AccountActivities.Delete' },
  listPath: '/crm/account-activities',
  createPath: '/crm/account-activities/create',
  detailsPath: (id) => `/crm/account-activities/${id}`,
  editPath: (id) => `/crm/account-activities/${id}/edit`,
  columns: [
    { key: 'subject', label: 'Subject', sortable: true },
    { key: 'accountId', label: 'Account Id', sortable: true },
    { key: 'activityDate', label: 'Activity Date', sortable: true },
    { key: 'statusId', label: 'Status Lookup Id', sortable: true },
  ],
  fields: [
    { key: 'accountId', label: 'Account Id', kind: 'text', required: true },
    { key: 'contactId', label: 'Contact Id', kind: 'text' },
    { key: 'activityTypeId', label: 'Activity Type Lookup Id', kind: 'text' },
    { key: 'subject', label: 'Subject', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'activityDate', label: 'Activity Date (ISO)', kind: 'text', required: true },
    { key: 'dueDate', label: 'Due Date (ISO)', kind: 'text' },
    { key: 'priorityId', label: 'Priority Lookup Id', kind: 'text' },
    { key: 'statusId', label: 'Status Lookup Id', kind: 'text' },
    { key: 'outcomeId', label: 'Outcome Lookup Id', kind: 'text' },
    { key: 'assignedToUserId', label: 'Assigned User Id', kind: 'text' },
    { key: 'relatedEntityType', label: 'Related Entity Type', kind: 'text' },
    { key: 'relatedEntityId', label: 'Related Entity Id', kind: 'text' },
    { key: 'isPrivate', label: 'Private', kind: 'checkbox' },
    { key: 'followUpRequired', label: 'Follow Up Required', kind: 'checkbox' },
    { key: 'followUpDate', label: 'Follow Up Date (ISO)', kind: 'text' },
  ],
  defaultForm: {
    accountId: '', contactId: '', activityTypeId: '', subject: '', description: '', activityDate: '', dueDate: '', priorityId: '', statusId: '', outcomeId: '', assignedToUserId: '', relatedEntityType: '', relatedEntityId: '', isPrivate: false, followUpRequired: false, followUpDate: '',
  },
  mapItemToForm: (item) => ({
    accountId: item.accountId,
    contactId: item.contactId ?? '',
    activityTypeId: item.activityTypeId ?? '',
    subject: item.subject,
    description: item.description ?? '',
    activityDate: item.activityDate,
    dueDate: item.dueDate ?? '',
    priorityId: item.priorityId ?? '',
    statusId: item.statusId ?? '',
    outcomeId: item.outcomeId ?? '',
    assignedToUserId: item.assignedToUserId ?? '',
    relatedEntityType: item.relatedEntityType ?? '',
    relatedEntityId: item.relatedEntityId ?? '',
    isPrivate: item.isPrivate,
    followUpRequired: item.followUpRequired,
    followUpDate: item.followUpDate ?? '',
  }),
  mapCreatePayload: (form) => ({
    accountId: String(form.accountId ?? ''),
    contactId: String(form.contactId ?? '') || null,
    activityTypeId: String(form.activityTypeId ?? '') || null,
    subject: String(form.subject ?? ''),
    description: String(form.description ?? '') || null,
    activityDate: String(form.activityDate ?? '') || new Date().toISOString(),
    dueDate: String(form.dueDate ?? '') || null,
    priorityId: String(form.priorityId ?? '') || null,
    statusId: String(form.statusId ?? '') || null,
    outcomeId: String(form.outcomeId ?? '') || null,
    assignedToUserId: String(form.assignedToUserId ?? '') || null,
    relatedEntityType: String(form.relatedEntityType ?? '') || null,
    relatedEntityId: String(form.relatedEntityId ?? '') || null,
    isPrivate: Boolean(form.isPrivate),
    followUpRequired: Boolean(form.followUpRequired),
    followUpDate: String(form.followUpDate ?? '') || null,
  }),
  mapUpdatePayload: (form, item) => {
    const payload = accountActivitiesConfig.mapCreatePayload(form) as Record<string, unknown>
    return { ...payload, id: item.id }
  },
  details: (item) => [
    { label: 'Account Id', value: item.accountId },
    { label: 'Subject', value: item.subject },
    { label: 'Activity Date', value: item.activityDate },
    { label: 'Status Lookup Id', value: item.statusId ?? '' },
    { label: 'Follow Up Required', value: item.followUpRequired ? 'Yes' : 'No' },
  ],
}
