import { statusCell, type DenseColumn } from '../grid/DenseDataGrid'
import type {
  Account,
  AccountActivity,
  AccountAddress,
  AccountRelationship,
  AuditLog,
  Case,
  CaseComment,
  Contact,
  CustomerProfile,
  Department,
  Discount,
  Invoice,
  LookupCategory,
  LookupValue,
  Order,
  PriceList,
  PriceListItem,
  Quote,
  Permission,
  Product,
  ProductBundle,
  ProductCategory,
  Role,
  SystemSetting,
  Team,
  UnitOfMeasure,
  User,
} from '../../types/models'

export type FieldKind = 'text' | 'textarea' | 'number' | 'checkbox' | 'select'

export type EntityField = {
  key: string
  label: string
  kind: FieldKind
  required?: boolean
  options?: Array<{ value: string; label: string }>
  readOnlyOnCreate?: boolean
  readOnlyOnEdit?: boolean
}

export type FormState = Record<string, string | number | boolean>

export type EntityConfig<TItem extends { id: string }> = {
  key: string
  title: string
  subtitle: string
  endpoint: string
  permissions: { view: string; create?: string; update?: string; delete?: string }
  listPath: string
  createPath: string
  detailsPath: (id: string) => string
  editPath: (id: string) => string
  columns: DenseColumn<TItem>[]
  fields: EntityField[]
  defaultForm: FormState
  mapItemToForm: (item: TItem) => FormState
  mapCreatePayload: (form: FormState) => unknown
  mapUpdatePayload: (form: FormState, item: TItem) => unknown
  details: (item: TItem) => Array<{ label: string; value: string }>
  listRowActions?: Array<{ key: string; label: string; to: (item: TItem) => string }>
  readOnly?: boolean
  generatedNumber?: { fieldKey: string; sequenceCode: string }
}

export const settingDataTypeOptions = [
  { value: '1', label: 'String' },
  { value: '2', label: 'Number' },
  { value: '3', label: 'Boolean' },
  { value: '4', label: 'Json' },
]

export const usersConfig: EntityConfig<User> = {
  key: 'users',
  title: 'Users',
  subtitle: 'Manage user accounts, lock status, and security assignments.',
  endpoint: 'api/users',
  permissions: { view: 'Users.View', create: 'Users.Create', update: 'Users.Update', delete: 'Users.Delete' },
  listPath: '/admin/users',
  createPath: '/admin/users/create',
  detailsPath: (id) => `/admin/users/${id}`,
  editPath: (id) => `/admin/users/${id}/edit`,
  columns: [
    { key: 'email', label: 'Email', sortable: true },
    { key: 'firstName', label: 'First Name', sortable: true },
    { key: 'lastName', label: 'Last Name', sortable: true },
    { key: 'isEnabled', label: 'Status', sortable: true, render: (row) => statusCell(row.isEnabled ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'email', label: 'Email', kind: 'text', required: true, readOnlyOnEdit: true },
    { key: 'password', label: 'Password', kind: 'text', required: true },
    { key: 'firstName', label: 'First Name', kind: 'text' },
    { key: 'lastName', label: 'Last Name', kind: 'text' },
    { key: 'isEnabled', label: 'Enabled', kind: 'checkbox' },
  ],
  defaultForm: { email: '', password: '', firstName: '', lastName: '', isEnabled: true },
  mapItemToForm: (item) => ({ email: item.email, password: '', firstName: item.firstName ?? '', lastName: item.lastName ?? '', isEnabled: item.isEnabled }),
  mapCreatePayload: (form) => ({
    email: String(form.email ?? ''),
    password: String(form.password ?? ''),
    firstName: String(form.firstName ?? ''),
    lastName: String(form.lastName ?? ''),
    isEnabled: Boolean(form.isEnabled),
  }),
  mapUpdatePayload: (form) => ({
    firstName: String(form.firstName ?? ''),
    lastName: String(form.lastName ?? ''),
    isEnabled: Boolean(form.isEnabled),
  }),
  details: (item) => [
    { label: 'Email', value: item.email },
    { label: 'First Name', value: item.firstName ?? '' },
    { label: 'Last Name', value: item.lastName ?? '' },
    { label: 'Enabled', value: item.isEnabled ? 'Yes' : 'No' },
    { label: 'Locked', value: item.isLocked ? 'Yes' : 'No' },
    { label: 'Roles', value: item.roles.join(', ') },
  ],
}

export const rolesConfig: EntityConfig<Role> = {
  key: 'roles',
  title: 'Roles',
  subtitle: 'Create and maintain role definitions.',
  endpoint: 'api/roles',
  permissions: { view: 'Roles.View', create: 'Roles.Create', update: 'Roles.Update', delete: 'Roles.Delete' },
  listPath: '/admin/roles',
  createPath: '/admin/roles/create',
  detailsPath: (id) => `/admin/roles/${id}`,
  editPath: (id) => `/admin/roles/${id}/edit`,
  columns: [
    { key: 'name', label: 'Name', sortable: true },
    { key: 'description', label: 'Description', sortable: true },
  ],
  fields: [
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
  ],
  defaultForm: { name: '', description: '' },
  mapItemToForm: (item) => ({ name: item.name, description: item.description ?? '' }),
  mapCreatePayload: (form) => ({ name: String(form.name ?? ''), description: String(form.description ?? '') || null }),
  mapUpdatePayload: (form) => ({ name: String(form.name ?? ''), description: String(form.description ?? '') || null }),
  details: (item) => [
    { label: 'Name', value: item.name },
    { label: 'Description', value: item.description ?? '' },
  ],
}

export const permissionsConfig: EntityConfig<Permission> = {
  key: 'permissions',
  title: 'Permissions',
  subtitle: 'Manage module/action permissions.',
  endpoint: 'api/permissions',
  permissions: { view: 'Roles.View', create: 'Roles.Create', update: 'Roles.Update', delete: 'Roles.Delete' },
  listPath: '/admin/permissions',
  createPath: '/admin/permissions/create',
  detailsPath: (id) => `/admin/permissions/${id}`,
  editPath: (id) => `/admin/permissions/${id}/edit`,
  columns: [
    { key: 'name', label: 'Permission', sortable: true },
    { key: 'module', label: 'Module', sortable: true },
    { key: 'action', label: 'Action', sortable: true },
  ],
  fields: [
    { key: 'module', label: 'Module', kind: 'text', required: true },
    { key: 'action', label: 'Action', kind: 'text', required: true },
  ],
  defaultForm: { module: '', action: '' },
  mapItemToForm: (item) => ({ module: item.module, action: item.action }),
  mapCreatePayload: (form) => ({ module: String(form.module ?? ''), action: String(form.action ?? '') }),
  mapUpdatePayload: (form) => ({ module: String(form.module ?? ''), action: String(form.action ?? '') }),
  details: (item) => [
    { label: 'Name', value: item.name },
    { label: 'Module', value: item.module },
    { label: 'Action', value: item.action },
  ],
}

export const teamsConfig: EntityConfig<Team> = {
  key: 'teams',
  title: 'Teams',
  subtitle: 'Configure team ownership and state.',
  endpoint: 'api/teams',
  permissions: { view: 'Teams.View', create: 'Teams.Create', update: 'Teams.Update', delete: 'Teams.Delete' },
  listPath: '/admin/teams',
  createPath: '/admin/teams/create',
  detailsPath: (id) => `/admin/teams/${id}`,
  editPath: (id) => `/admin/teams/${id}/edit`,
  columns: [
    { key: 'name', label: 'Name', sortable: true },
    { key: 'description', label: 'Description', sortable: true },
    { key: 'ownerUserId', label: 'Owner User Id', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'ownerUserId', label: 'Owner User Id', kind: 'text' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: { name: '', description: '', ownerUserId: '', isActive: true },
  mapItemToForm: (item) => ({ name: item.name, description: item.description ?? '', ownerUserId: item.ownerUserId ?? '', isActive: item.isActive }),
  mapCreatePayload: (form) => ({
    name: String(form.name ?? ''),
    description: String(form.description ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => ({
    name: String(form.name ?? ''),
    description: String(form.description ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  details: (item) => [
    { label: 'Name', value: item.name },
    { label: 'Description', value: item.description ?? '' },
    { label: 'Owner User Id', value: item.ownerUserId ?? '' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const departmentsConfig: EntityConfig<Department> = {
  key: 'departments',
  title: 'Departments',
  subtitle: 'Maintain department hierarchy and status.',
  endpoint: 'api/departments',
  permissions: { view: 'Departments.View', create: 'Departments.Create', update: 'Departments.Update', delete: 'Departments.Delete' },
  listPath: '/admin/departments',
  createPath: '/admin/departments/create',
  detailsPath: (id) => `/admin/departments/${id}`,
  editPath: (id) => `/admin/departments/${id}/edit`,
  columns: [
    { key: 'name', label: 'Name', sortable: true },
    { key: 'description', label: 'Description', sortable: true },
    { key: 'parentDepartmentId', label: 'Parent Department Id', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'parentDepartmentId', label: 'Parent Department Id', kind: 'text' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: { name: '', description: '', parentDepartmentId: '', isActive: true },
  mapItemToForm: (item) => ({ name: item.name, description: item.description ?? '', parentDepartmentId: item.parentDepartmentId ?? '', isActive: item.isActive }),
  mapCreatePayload: (form) => ({
    name: String(form.name ?? ''),
    description: String(form.description ?? '') || null,
    parentDepartmentId: String(form.parentDepartmentId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => ({
    name: String(form.name ?? ''),
    description: String(form.description ?? '') || null,
    parentDepartmentId: String(form.parentDepartmentId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  details: (item) => [
    { label: 'Name', value: item.name },
    { label: 'Description', value: item.description ?? '' },
    { label: 'Parent Department Id', value: item.parentDepartmentId ?? '' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const settingsConfig: EntityConfig<SystemSetting> = {
  key: 'system-settings',
  title: 'System Settings',
  subtitle: 'Configure global key/value settings.',
  endpoint: 'api/system-settings',
  permissions: { view: 'Settings.View', create: 'Settings.Update', update: 'Settings.Update', delete: 'Settings.Update' },
  listPath: '/admin/system-settings',
  createPath: '/admin/system-settings/create',
  detailsPath: (id) => `/admin/system-settings/${id}`,
  editPath: (id) => `/admin/system-settings/${id}/edit`,
  columns: [
    { key: 'category', label: 'Category', sortable: true },
    { key: 'key', label: 'Key', sortable: true },
    { key: 'value', label: 'Value', sortable: true },
    { key: 'dataType', label: 'Data Type', sortable: true, render: (row) => settingDataTypeOptions.find((x) => Number(x.value) === row.dataType)?.label ?? String(row.dataType) },
  ],
  fields: [
    { key: 'category', label: 'Category', kind: 'text', required: true },
    { key: 'key', label: 'Key', kind: 'text', required: true },
    { key: 'value', label: 'Value', kind: 'textarea', required: true },
    { key: 'dataType', label: 'Data Type', kind: 'select', required: true, options: settingDataTypeOptions },
    { key: 'description', label: 'Description', kind: 'textarea' },
  ],
  defaultForm: { category: '', key: '', value: '', dataType: '1', description: '' },
  mapItemToForm: (item) => ({ category: item.category, key: item.key, value: item.value, dataType: String(item.dataType), description: item.description ?? '' }),
  mapCreatePayload: (form) => ({
    category: String(form.category ?? ''),
    key: String(form.key ?? ''),
    value: String(form.value ?? ''),
    dataType: Number(form.dataType ?? 1),
    description: String(form.description ?? '') || null,
  }),
  mapUpdatePayload: (form) => ({
    category: String(form.category ?? ''),
    key: String(form.key ?? ''),
    value: String(form.value ?? ''),
    dataType: Number(form.dataType ?? 1),
    description: String(form.description ?? '') || null,
  }),
  details: (item) => [
    { label: 'Category', value: item.category },
    { label: 'Key', value: item.key },
    { label: 'Value', value: item.value },
    { label: 'Data Type', value: settingDataTypeOptions.find((x) => Number(x.value) === item.dataType)?.label ?? String(item.dataType) },
    { label: 'Description', value: item.description ?? '' },
  ],
}

export const lookupCategoriesConfig: EntityConfig<LookupCategory> = {
  key: 'lookup-categories',
  title: 'Lookup Categories',
  subtitle: 'Manage reference data categories.',
  endpoint: 'api/lookup-categories',
  permissions: { view: 'ReferenceData.View', create: 'ReferenceData.Create', update: 'ReferenceData.Update', delete: 'ReferenceData.Delete' },
  listPath: '/admin/lookup-categories',
  createPath: '/admin/lookup-categories/create',
  detailsPath: (id) => `/admin/lookup-categories/${id}`,
  editPath: (id) => `/admin/lookup-categories/${id}/edit`,
  columns: [
    { key: 'name', label: 'Name', sortable: true },
    { key: 'code', label: 'Code', sortable: true },
    { key: 'description', label: 'Description', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'code', label: 'Code', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: { name: '', code: '', description: '', isActive: true },
  mapItemToForm: (item) => ({ name: item.name, code: item.code, description: item.description ?? '', isActive: item.isActive }),
  mapCreatePayload: (form) => ({ name: String(form.name ?? ''), code: String(form.code ?? ''), description: String(form.description ?? '') || null, isActive: Boolean(form.isActive) }),
  mapUpdatePayload: (form) => ({ name: String(form.name ?? ''), code: String(form.code ?? ''), description: String(form.description ?? '') || null, isActive: Boolean(form.isActive) }),
  details: (item) => [
    { label: 'Name', value: item.name },
    { label: 'Code', value: item.code },
    { label: 'Description', value: item.description ?? '' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const lookupValuesConfig: EntityConfig<LookupValue> = {
  key: 'lookup-values',
  title: 'Lookup Values',
  subtitle: 'Manage values and sort order in reference categories.',
  endpoint: 'api/lookup-values',
  permissions: { view: 'ReferenceData.View', create: 'ReferenceData.Create', update: 'ReferenceData.Update', delete: 'ReferenceData.Delete' },
  listPath: '/admin/lookup-values',
  createPath: '/admin/lookup-values/create',
  detailsPath: (id) => `/admin/lookup-values/${id}`,
  editPath: (id) => `/admin/lookup-values/${id}/edit`,
  columns: [
    { key: 'name', label: 'Name', sortable: true },
    { key: 'code', label: 'Code', sortable: true },
    { key: 'sortOrder', label: 'Sort', sortable: true },
    { key: 'isDefault', label: 'Default', sortable: true, render: (row) => statusCell(row.isDefault ? 'Default' : 'No') },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'lookupCategoryId', label: 'Lookup Category Id', kind: 'text', required: true },
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'code', label: 'Code', kind: 'text', required: true },
    { key: 'sortOrder', label: 'Sort Order', kind: 'number' },
    { key: 'isDefault', label: 'Default', kind: 'checkbox' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: { lookupCategoryId: '', name: '', code: '', sortOrder: 0, isDefault: false, isActive: true },
  mapItemToForm: (item) => ({ lookupCategoryId: item.lookupCategoryId, name: item.name, code: item.code, sortOrder: item.sortOrder, isDefault: item.isDefault, isActive: item.isActive }),
  mapCreatePayload: (form) => ({
    lookupCategoryId: String(form.lookupCategoryId ?? ''),
    name: String(form.name ?? ''),
    code: String(form.code ?? ''),
    sortOrder: Number(form.sortOrder ?? 0),
    isDefault: Boolean(form.isDefault),
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => ({
    lookupCategoryId: String(form.lookupCategoryId ?? ''),
    name: String(form.name ?? ''),
    code: String(form.code ?? ''),
    sortOrder: Number(form.sortOrder ?? 0),
    isDefault: Boolean(form.isDefault),
    isActive: Boolean(form.isActive),
  }),
  details: (item) => [
    { label: 'Lookup Category Id', value: item.lookupCategoryId },
    { label: 'Name', value: item.name },
    { label: 'Code', value: item.code },
    { label: 'Sort Order', value: String(item.sortOrder) },
    { label: 'Default', value: item.isDefault ? 'Yes' : 'No' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const auditLogsConfig: EntityConfig<AuditLog> = {
  key: 'audit-logs',
  title: 'Audit Logs',
  subtitle: 'Review immutable audit history records.',
  endpoint: 'api/audit-logs',
  permissions: { view: 'AuditLogs.View' },
  listPath: '/admin/audit-logs',
  createPath: '/admin/audit-logs/create',
  detailsPath: (id) => `/admin/audit-logs/${id}`,
  editPath: (id) => `/admin/audit-logs/${id}/edit`,
  columns: [
    { key: 'entityName', label: 'Entity', sortable: true },
    { key: 'entityId', label: 'Entity Id', sortable: true },
    { key: 'action', label: 'Action', sortable: true },
    { key: 'createdAt', label: 'Created At', sortable: true },
  ],
  fields: [],
  defaultForm: {},
  mapItemToForm: () => ({}),
  mapCreatePayload: () => ({}),
  mapUpdatePayload: () => ({}),
  details: (item) => [
    { label: 'Entity', value: item.entityName },
    { label: 'Entity Id', value: item.entityId },
    { label: 'Action', value: item.action },
    { label: 'Created At', value: item.createdAt },
    { label: 'User Id', value: item.userId ?? '' },
    { label: 'IP Address', value: item.ipAddress ?? '' },
    { label: 'User Agent', value: item.userAgent ?? '' },
    { label: 'Old Values', value: item.oldValues ?? '' },
    { label: 'New Values', value: item.newValues ?? '' },
  ],
  readOnly: true,
}

export const accountsConfig: EntityConfig<Account> = {
  key: 'accounts',
  title: 'Accounts',
  subtitle: 'Manage customer and organization accounts.',
  endpoint: 'api/accounts',
  permissions: { view: 'Accounts.View', create: 'Accounts.Create', update: 'Accounts.Update', delete: 'Accounts.Delete' },
  listPath: '/crm/accounts',
  createPath: '/crm/accounts/create',
  detailsPath: (id) => `/crm/accounts/${id}`,
  editPath: (id) => `/crm/accounts/${id}/edit`,
  generatedNumber: { fieldKey: 'accountNumber', sequenceCode: 'ACCOUNT' },
  columns: [
    { key: 'accountNumber', label: 'Account #', sortable: true },
    { key: 'name', label: 'Name', sortable: true },
    { key: 'email', label: 'Email', sortable: true },
    { key: 'mainPhone', label: 'Main Phone', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'accountNumber', label: 'Account Number', kind: 'text', required: true, readOnlyOnCreate: true, readOnlyOnEdit: true },
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'legalName', label: 'Legal Name', kind: 'text' },
    { key: 'tradingName', label: 'Trading Name', kind: 'text' },
    { key: 'accountTypeId', label: 'Account Type Lookup Id', kind: 'text' },
    { key: 'industryId', label: 'Industry Lookup Id', kind: 'text' },
    { key: 'ownershipTypeId', label: 'Ownership Type Lookup Id', kind: 'text' },
    { key: 'customerStatusId', label: 'Customer Status Lookup Id', kind: 'text' },
    { key: 'customerSegmentId', label: 'Customer Segment Lookup Id', kind: 'text' },
    { key: 'website', label: 'Website', kind: 'text' },
    { key: 'mainPhone', label: 'Main Phone', kind: 'text' },
    { key: 'alternatePhone', label: 'Alternate Phone', kind: 'text' },
    { key: 'email', label: 'Email', kind: 'text' },
    { key: 'fax', label: 'Fax', kind: 'text' },
    { key: 'taxNumber', label: 'Tax Number', kind: 'text' },
    { key: 'registrationNumber', label: 'Registration Number', kind: 'text' },
    { key: 'annualRevenue', label: 'Annual Revenue', kind: 'number' },
    { key: 'numberOfEmployees', label: 'Employees', kind: 'number' },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'parentAccountId', label: 'Parent Account Id', kind: 'text' },
    { key: 'primaryContactId', label: 'Primary Contact Id', kind: 'text' },
    { key: 'ownerUserId', label: 'Owner User Id', kind: 'text' },
    { key: 'ownerTeamId', label: 'Owner Team Id', kind: 'text' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: {
    accountNumber: '', name: '', legalName: '', tradingName: '', accountTypeId: '', industryId: '', ownershipTypeId: '', customerStatusId: '', customerSegmentId: '',
    website: '', mainPhone: '', alternatePhone: '', email: '', fax: '', taxNumber: '', registrationNumber: '', annualRevenue: 0, numberOfEmployees: 0,
    description: '', parentAccountId: '', primaryContactId: '', ownerUserId: '', ownerTeamId: '', isActive: true,
  },
  mapItemToForm: (item) => ({
    accountNumber: item.accountNumber, name: item.name, legalName: item.legalName ?? '', tradingName: item.tradingName ?? '', accountTypeId: item.accountTypeId ?? '',
    industryId: item.industryId ?? '', ownershipTypeId: item.ownershipTypeId ?? '', customerStatusId: item.customerStatusId ?? '', customerSegmentId: item.customerSegmentId ?? '',
    website: item.website ?? '', mainPhone: item.mainPhone ?? '', alternatePhone: item.alternatePhone ?? '', email: item.email ?? '', fax: item.fax ?? '', taxNumber: item.taxNumber ?? '',
    registrationNumber: item.registrationNumber ?? '', annualRevenue: item.annualRevenue ?? 0, numberOfEmployees: item.numberOfEmployees ?? 0,
    description: item.description ?? '', parentAccountId: item.parentAccountId ?? '', primaryContactId: item.primaryContactId ?? '', ownerUserId: item.ownerUserId ?? '', ownerTeamId: item.ownerTeamId ?? '', isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    accountNumber: String(form.accountNumber ?? ''),
    name: String(form.name ?? ''),
    legalName: String(form.legalName ?? '') || null,
    tradingName: String(form.tradingName ?? '') || null,
    accountTypeId: String(form.accountTypeId ?? '') || null,
    industryId: String(form.industryId ?? '') || null,
    ownershipTypeId: String(form.ownershipTypeId ?? '') || null,
    customerStatusId: String(form.customerStatusId ?? '') || null,
    customerSegmentId: String(form.customerSegmentId ?? '') || null,
    website: String(form.website ?? '') || null,
    mainPhone: String(form.mainPhone ?? '') || null,
    alternatePhone: String(form.alternatePhone ?? '') || null,
    email: String(form.email ?? '') || null,
    fax: String(form.fax ?? '') || null,
    taxNumber: String(form.taxNumber ?? '') || null,
    registrationNumber: String(form.registrationNumber ?? '') || null,
    annualRevenue: Number(form.annualRevenue ?? 0) || null,
    numberOfEmployees: Number(form.numberOfEmployees ?? 0) || null,
    description: String(form.description ?? '') || null,
    parentAccountId: String(form.parentAccountId ?? '') || null,
    primaryContactId: String(form.primaryContactId ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    ownerTeamId: String(form.ownerTeamId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => ({
    accountNumber: String(form.accountNumber ?? ''),
    name: String(form.name ?? ''),
    legalName: String(form.legalName ?? '') || null,
    tradingName: String(form.tradingName ?? '') || null,
    accountTypeId: String(form.accountTypeId ?? '') || null,
    industryId: String(form.industryId ?? '') || null,
    ownershipTypeId: String(form.ownershipTypeId ?? '') || null,
    customerStatusId: String(form.customerStatusId ?? '') || null,
    customerSegmentId: String(form.customerSegmentId ?? '') || null,
    website: String(form.website ?? '') || null,
    mainPhone: String(form.mainPhone ?? '') || null,
    alternatePhone: String(form.alternatePhone ?? '') || null,
    email: String(form.email ?? '') || null,
    fax: String(form.fax ?? '') || null,
    taxNumber: String(form.taxNumber ?? '') || null,
    registrationNumber: String(form.registrationNumber ?? '') || null,
    annualRevenue: Number(form.annualRevenue ?? 0) || null,
    numberOfEmployees: Number(form.numberOfEmployees ?? 0) || null,
    description: String(form.description ?? '') || null,
    parentAccountId: String(form.parentAccountId ?? '') || null,
    primaryContactId: String(form.primaryContactId ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    ownerTeamId: String(form.ownerTeamId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  details: (item) => [
    { label: 'Account Number', value: item.accountNumber },
    { label: 'Name', value: item.name },
    { label: 'Legal Name', value: item.legalName ?? '' },
    { label: 'Trading Name', value: item.tradingName ?? '' },
    { label: 'Email', value: item.email ?? '' },
    { label: 'Main Phone', value: item.mainPhone ?? '' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const contactsConfig: EntityConfig<Contact> = {
  key: 'contacts',
  title: 'Contacts',
  subtitle: 'Manage account contacts and communication preferences.',
  endpoint: 'api/contacts',
  permissions: { view: 'Contacts.View', create: 'Contacts.Create', update: 'Contacts.Update', delete: 'Contacts.Delete' },
  listPath: '/contacts',
  createPath: '/contacts/create',
  detailsPath: (id) => `/contacts/${id}`,
  editPath: (id) => `/contacts/${id}/edit`,
  columns: [
    { key: 'contactNumber', label: 'Contact #', sortable: true },
    { key: 'fullName', label: 'Full Name', sortable: true },
    { key: 'accountName', label: 'Account', sortable: true },
    { key: 'jobTitle', label: 'Job Title', sortable: true },
    { key: 'email', label: 'Email', sortable: true },
    { key: 'mobilePhone', label: 'Mobile', sortable: true },
    { key: 'preferredContactMethodName', label: 'Preferred Method', sortable: true },
    { key: 'contactRoleName', label: 'Role', sortable: true },
    { key: 'isPrimaryContact', label: 'Primary', sortable: true, render: (row) => statusCell(row.isPrimaryContact ? 'Primary' : 'No') },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'contactNumber', label: 'Contact Number', kind: 'text', required: true },
    { key: 'accountId', label: 'Account', kind: 'text', required: true },
    { key: 'contactRoleId', label: 'Contact Role', kind: 'text' },
    { key: 'salutationLookupId', label: 'Salutation', kind: 'text' },
    { key: 'genderLookupId', label: 'Gender', kind: 'text' },
    { key: 'firstName', label: 'First Name', kind: 'text', required: true },
    { key: 'middleName', label: 'Middle Name', kind: 'text' },
    { key: 'lastName', label: 'Last Name', kind: 'text', required: true },
    { key: 'preferredName', label: 'Preferred Name', kind: 'text' },
    { key: 'jobTitle', label: 'Job Title', kind: 'text' },
    { key: 'department', label: 'Department', kind: 'text' },
    { key: 'email', label: 'Email', kind: 'text' },
    { key: 'alternateEmail', label: 'Alternate Email', kind: 'text' },
    { key: 'workPhone', label: 'Work Phone', kind: 'text' },
    { key: 'mobilePhone', label: 'Mobile Phone', kind: 'text' },
    { key: 'homePhone', label: 'Home Phone', kind: 'text' },
    { key: 'fax', label: 'Fax', kind: 'text' },
    { key: 'preferredContactMethodId', label: 'Preferred Contact Method', kind: 'text' },
    { key: 'preferredLanguageId', label: 'Preferred Language', kind: 'text' },
    { key: 'preferredTimeZoneId', label: 'Preferred Time Zone', kind: 'text' },
    { key: 'marketingConsent', label: 'Marketing Consent', kind: 'checkbox' },
    { key: 'emailOptIn', label: 'Email Opt-In', kind: 'checkbox' },
    { key: 'smsOptIn', label: 'SMS Opt-In', kind: 'checkbox' },
    { key: 'phoneOptIn', label: 'Phone Opt-In', kind: 'checkbox' },
    { key: 'isPrimaryContact', label: 'Primary Contact', kind: 'checkbox' },
    { key: 'dateOfBirth', label: 'Date Of Birth (ISO)', kind: 'text' },
    { key: 'notes', label: 'Notes', kind: 'textarea' },
    { key: 'ownerUserId', label: 'Owner User Id', kind: 'text' },
    { key: 'ownerTeamId', label: 'Owner Team Id', kind: 'text' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: {
    contactNumber: '', accountId: '', contactRoleId: '', salutationLookupId: '', genderLookupId: '', firstName: '', middleName: '', lastName: '', preferredName: '',
    jobTitle: '', department: '', email: '', alternateEmail: '', workPhone: '', mobilePhone: '', homePhone: '', fax: '', preferredContactMethodId: '', preferredLanguageId: '', preferredTimeZoneId: '',
    marketingConsent: false, emailOptIn: false, smsOptIn: false, phoneOptIn: false, isPrimaryContact: false, dateOfBirth: '', notes: '', ownerUserId: '', ownerTeamId: '', isActive: true,
  },
  mapItemToForm: (item) => ({
    contactNumber: item.contactNumber, accountId: item.accountId, contactRoleId: item.contactRoleId ?? '', salutationLookupId: item.salutationLookupId ?? '', genderLookupId: item.genderLookupId ?? '',
    firstName: item.firstName, middleName: item.middleName ?? '', lastName: item.lastName, preferredName: item.preferredName ?? '', jobTitle: item.jobTitle ?? '', department: item.department ?? '',
    email: item.email ?? '', alternateEmail: item.alternateEmail ?? '', workPhone: item.workPhone ?? '', mobilePhone: item.mobilePhone ?? '', homePhone: item.homePhone ?? '', fax: item.fax ?? '',
    preferredContactMethodId: item.preferredContactMethodId ?? '', preferredLanguageId: item.preferredLanguageId ?? '', preferredTimeZoneId: item.preferredTimeZoneId ?? '',
    marketingConsent: item.marketingConsent, emailOptIn: item.emailOptIn, smsOptIn: item.smsOptIn, phoneOptIn: item.phoneOptIn, isPrimaryContact: item.isPrimaryContact,
    dateOfBirth: item.dateOfBirth ?? '', notes: item.notes ?? '', ownerUserId: item.ownerUserId ?? '', ownerTeamId: item.ownerTeamId ?? '', isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    contactNumber: String(form.contactNumber ?? ''),
    accountId: String(form.accountId ?? ''),
    contactRoleId: String(form.contactRoleId ?? '') || null,
    salutationLookupId: String(form.salutationLookupId ?? '') || null,
    genderLookupId: String(form.genderLookupId ?? '') || null,
    firstName: String(form.firstName ?? ''),
    middleName: String(form.middleName ?? '') || null,
    lastName: String(form.lastName ?? ''),
    preferredName: String(form.preferredName ?? '') || null,
    jobTitle: String(form.jobTitle ?? '') || null,
    department: String(form.department ?? '') || null,
    email: String(form.email ?? '') || null,
    alternateEmail: String(form.alternateEmail ?? '') || null,
    workPhone: String(form.workPhone ?? '') || null,
    mobilePhone: String(form.mobilePhone ?? '') || null,
    homePhone: String(form.homePhone ?? '') || null,
    fax: String(form.fax ?? '') || null,
    preferredContactMethodId: String(form.preferredContactMethodId ?? '') || null,
    preferredLanguageId: String(form.preferredLanguageId ?? '') || null,
    preferredTimeZoneId: String(form.preferredTimeZoneId ?? '') || null,
    marketingConsent: Boolean(form.marketingConsent),
    emailOptIn: Boolean(form.emailOptIn),
    smsOptIn: Boolean(form.smsOptIn),
    phoneOptIn: Boolean(form.phoneOptIn),
    isPrimaryContact: Boolean(form.isPrimaryContact),
    dateOfBirth: String(form.dateOfBirth ?? '') || null,
    notes: String(form.notes ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    ownerTeamId: String(form.ownerTeamId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form, item) => {
    const payload = contactsConfig.mapCreatePayload(form) as Record<string, unknown>
    return { ...payload, id: item.id }
  },
  details: (item) => [
    { label: 'Contact Number', value: item.contactNumber },
    { label: 'Name', value: item.fullName },
    { label: 'Account', value: item.accountName ?? '' },
    { label: 'Role', value: item.contactRoleName ?? '' },
    { label: 'Email', value: item.email ?? '' },
    { label: 'Mobile Phone', value: item.mobilePhone ?? '' },
    { label: 'Preferred Method', value: item.preferredContactMethodName ?? '' },
    { label: 'Primary Contact', value: item.isPrimaryContact ? 'Yes' : 'No' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const accountAddressesConfig: EntityConfig<AccountAddress> = {
  key: 'account-addresses',
  title: 'Account Addresses',
  subtitle: 'Manage billing, shipping, and service addresses.',
  endpoint: 'api/account-addresses',
  permissions: { view: 'AccountAddresses.View', create: 'AccountAddresses.Create', update: 'AccountAddresses.Update', delete: 'AccountAddresses.Delete' },
  listPath: '/crm/account-addresses',
  createPath: '/crm/account-addresses/create',
  detailsPath: (id) => `/crm/account-addresses/${id}`,
  editPath: (id) => `/crm/account-addresses/${id}/edit`,
  columns: [
    { key: 'line1', label: 'Address Line 1', sortable: true },
    { key: 'city', label: 'City', sortable: true },
    { key: 'stateProvince', label: 'State/Province', sortable: true },
    { key: 'postalCode', label: 'Postal Code', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'accountId', label: 'Account Id', kind: 'text', required: true },
    { key: 'addressTypeId', label: 'Address Type Lookup Id', kind: 'text' },
    { key: 'attentionTo', label: 'Attention To', kind: 'text' },
    { key: 'line1', label: 'Line 1', kind: 'text', required: true },
    { key: 'line2', label: 'Line 2', kind: 'text' },
    { key: 'landmark', label: 'Landmark', kind: 'text' },
    { key: 'city', label: 'City', kind: 'text' },
    { key: 'stateProvince', label: 'State/Province', kind: 'text' },
    { key: 'postalCode', label: 'Postal Code', kind: 'text' },
    { key: 'countryId', label: 'Country Lookup Id', kind: 'text' },
    { key: 'latitude', label: 'Latitude', kind: 'number' },
    { key: 'longitude', label: 'Longitude', kind: 'number' },
    { key: 'isPrimary', label: 'Primary', kind: 'checkbox' },
    { key: 'isBilling', label: 'Billing', kind: 'checkbox' },
    { key: 'isShipping', label: 'Shipping', kind: 'checkbox' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: {
    accountId: '', addressTypeId: '', attentionTo: '', line1: '', line2: '', landmark: '', city: '', stateProvince: '', postalCode: '', countryId: '', latitude: 0, longitude: 0,
    isPrimary: false, isBilling: false, isShipping: false, isActive: true,
  },
  mapItemToForm: (item) => ({
    accountId: item.accountId, addressTypeId: item.addressTypeId ?? '', attentionTo: item.attentionTo ?? '', line1: item.line1, line2: item.line2 ?? '', landmark: item.landmark ?? '', city: item.city ?? '', stateProvince: item.stateProvince ?? '',
    postalCode: item.postalCode ?? '', countryId: item.countryId ?? '', latitude: item.latitude ?? 0, longitude: item.longitude ?? 0, isPrimary: item.isPrimary, isBilling: item.isBilling, isShipping: item.isShipping, isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    accountId: String(form.accountId ?? ''),
    addressTypeId: String(form.addressTypeId ?? '') || null,
    attentionTo: String(form.attentionTo ?? '') || null,
    line1: String(form.line1 ?? ''),
    line2: String(form.line2 ?? '') || null,
    landmark: String(form.landmark ?? '') || null,
    city: String(form.city ?? '') || null,
    stateProvince: String(form.stateProvince ?? '') || null,
    postalCode: String(form.postalCode ?? '') || null,
    countryId: String(form.countryId ?? '') || null,
    latitude: Number(form.latitude ?? 0) || null,
    longitude: Number(form.longitude ?? 0) || null,
    isPrimary: Boolean(form.isPrimary),
    isBilling: Boolean(form.isBilling),
    isShipping: Boolean(form.isShipping),
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form, item) => {
    const payload = accountAddressesConfig.mapCreatePayload(form) as Record<string, unknown>
    return { ...payload, id: item.id }
  },
  details: (item) => [
    { label: 'Account Id', value: item.accountId },
    { label: 'Address', value: `${item.line1}${item.city ? `, ${item.city}` : ''}` },
    { label: 'Postal Code', value: item.postalCode ?? '' },
    { label: 'Primary', value: item.isPrimary ? 'Yes' : 'No' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const customerProfilesConfig: EntityConfig<CustomerProfile> = {
  key: 'customer-profiles',
  title: 'Customer Profiles',
  subtitle: 'Manage customer financial and lifecycle profile attributes.',
  endpoint: 'api/customer-profiles',
  permissions: { view: 'CustomerProfiles.View', create: 'CustomerProfiles.Create', update: 'CustomerProfiles.Update', delete: 'CustomerProfiles.Delete' },
  listPath: '/crm/customer-profiles',
  createPath: '/crm/customer-profiles/create',
  detailsPath: (id) => `/crm/customer-profiles/${id}`,
  editPath: (id) => `/crm/customer-profiles/${id}/edit`,
  columns: [
    { key: 'accountId', label: 'Account Id', sortable: true },
    { key: 'creditLimit', label: 'Credit Limit', sortable: true },
    { key: 'customerSince', label: 'Customer Since', sortable: true },
  ],
  fields: [
    { key: 'accountId', label: 'Account Id', kind: 'text', required: true },
    { key: 'creditLimit', label: 'Credit Limit', kind: 'number' },
    { key: 'paymentTermsId', label: 'Payment Terms Lookup Id', kind: 'text' },
    { key: 'preferredCurrencyId', label: 'Preferred Currency Lookup Id', kind: 'text' },
    { key: 'preferredLanguageId', label: 'Preferred Language Lookup Id', kind: 'text' },
    { key: 'timeZoneId', label: 'Time Zone Lookup Id', kind: 'text' },
    { key: 'riskRatingId', label: 'Risk Rating Lookup Id', kind: 'text' },
    { key: 'lifecycleStageId', label: 'Lifecycle Stage Lookup Id', kind: 'text' },
    { key: 'customerSince', label: 'Customer Since (ISO)', kind: 'text' },
    { key: 'lastReviewDate', label: 'Last Review Date (ISO)', kind: 'text' },
    { key: 'nextReviewDate', label: 'Next Review Date (ISO)', kind: 'text' },
    { key: 'churnRiskScore', label: 'Churn Risk Score', kind: 'number' },
    { key: 'satisfactionScore', label: 'Satisfaction Score', kind: 'number' },
    { key: 'notes', label: 'Notes', kind: 'textarea' },
  ],
  defaultForm: {
    accountId: '', creditLimit: 0, paymentTermsId: '', preferredCurrencyId: '', preferredLanguageId: '', timeZoneId: '', riskRatingId: '', lifecycleStageId: '',
    customerSince: '', lastReviewDate: '', nextReviewDate: '', churnRiskScore: 0, satisfactionScore: 0, notes: '',
  },
  mapItemToForm: (item) => ({
    accountId: item.accountId, creditLimit: item.creditLimit ?? 0, paymentTermsId: item.paymentTermsId ?? '', preferredCurrencyId: item.preferredCurrencyId ?? '',
    preferredLanguageId: item.preferredLanguageId ?? '', timeZoneId: item.timeZoneId ?? '', riskRatingId: item.riskRatingId ?? '', lifecycleStageId: item.lifecycleStageId ?? '',
    customerSince: item.customerSince ?? '', lastReviewDate: item.lastReviewDate ?? '', nextReviewDate: item.nextReviewDate ?? '', churnRiskScore: item.churnRiskScore ?? 0, satisfactionScore: item.satisfactionScore ?? 0, notes: item.notes ?? '',
  }),
  mapCreatePayload: (form) => ({
    accountId: String(form.accountId ?? ''),
    creditLimit: Number(form.creditLimit ?? 0) || null,
    paymentTermsId: String(form.paymentTermsId ?? '') || null,
    preferredCurrencyId: String(form.preferredCurrencyId ?? '') || null,
    preferredLanguageId: String(form.preferredLanguageId ?? '') || null,
    timeZoneId: String(form.timeZoneId ?? '') || null,
    riskRatingId: String(form.riskRatingId ?? '') || null,
    lifecycleStageId: String(form.lifecycleStageId ?? '') || null,
    customerSince: String(form.customerSince ?? '') || null,
    lastReviewDate: String(form.lastReviewDate ?? '') || null,
    nextReviewDate: String(form.nextReviewDate ?? '') || null,
    churnRiskScore: Number(form.churnRiskScore ?? 0) || null,
    satisfactionScore: Number(form.satisfactionScore ?? 0) || null,
    notes: String(form.notes ?? '') || null,
  }),
  mapUpdatePayload: (form, item) => {
    const payload = customerProfilesConfig.mapCreatePayload(form) as Record<string, unknown>
    return { ...payload, id: item.id }
  },
  details: (item) => [
    { label: 'Account Id', value: item.accountId },
    { label: 'Credit Limit', value: String(item.creditLimit ?? '') },
    { label: 'Customer Since', value: item.customerSince ?? '' },
    { label: 'Notes', value: item.notes ?? '' },
  ],
}

export const accountRelationshipsConfig: EntityConfig<AccountRelationship> = {
  key: 'account-relationships',
  title: 'Account Relationships',
  subtitle: 'Track relationship links between accounts.',
  endpoint: 'api/account-relationships',
  permissions: { view: 'AccountRelationships.View', create: 'AccountRelationships.Create', update: 'AccountRelationships.Update', delete: 'AccountRelationships.Delete' },
  listPath: '/crm/account-relationships',
  createPath: '/crm/account-relationships/create',
  detailsPath: (id) => `/crm/account-relationships/${id}`,
  editPath: (id) => `/crm/account-relationships/${id}/edit`,
  columns: [
    { key: 'sourceAccountId', label: 'Source Account', sortable: true },
    { key: 'targetAccountId', label: 'Target Account', sortable: true },
    { key: 'relationshipTypeId', label: 'Type Lookup Id', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Disabled') },
  ],
  fields: [
    { key: 'sourceAccountId', label: 'Source Account Id', kind: 'text', required: true },
    { key: 'targetAccountId', label: 'Target Account Id', kind: 'text', required: true },
    { key: 'relationshipTypeId', label: 'Relationship Type Lookup Id', kind: 'text' },
    { key: 'startDate', label: 'Start Date (ISO)', kind: 'text' },
    { key: 'endDate', label: 'End Date (ISO)', kind: 'text' },
    { key: 'strengthId', label: 'Strength Lookup Id', kind: 'text' },
    { key: 'notes', label: 'Notes', kind: 'textarea' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: { sourceAccountId: '', targetAccountId: '', relationshipTypeId: '', startDate: '', endDate: '', strengthId: '', notes: '', isActive: true },
  mapItemToForm: (item) => ({
    sourceAccountId: item.sourceAccountId,
    targetAccountId: item.targetAccountId,
    relationshipTypeId: item.relationshipTypeId ?? '',
    startDate: item.startDate ?? '',
    endDate: item.endDate ?? '',
    strengthId: item.strengthId ?? '',
    notes: item.notes ?? '',
    isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    sourceAccountId: String(form.sourceAccountId ?? ''),
    targetAccountId: String(form.targetAccountId ?? ''),
    relationshipTypeId: String(form.relationshipTypeId ?? '') || null,
    startDate: String(form.startDate ?? '') || null,
    endDate: String(form.endDate ?? '') || null,
    strengthId: String(form.strengthId ?? '') || null,
    notes: String(form.notes ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form, item) => {
    const payload = accountRelationshipsConfig.mapCreatePayload(form) as Record<string, unknown>
    return { ...payload, id: item.id }
  },
  details: (item) => [
    { label: 'Source Account Id', value: item.sourceAccountId },
    { label: 'Target Account Id', value: item.targetAccountId },
    { label: 'Relationship Type', value: item.relationshipTypeId ?? '' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const accountActivitiesConfig: EntityConfig<AccountActivity> = {
  key: 'account-activities',
  title: 'Account Activities',
  subtitle: 'Track interactions and follow-up actions for accounts.',
  endpoint: 'api/account-activities',
  permissions: { view: 'AccountActivities.View', create: 'AccountActivities.Create', update: 'AccountActivities.Update', delete: 'AccountActivities.Delete' },
  listPath: '/crm/account-activities',
  createPath: '/crm/account-activities/create',
  detailsPath: (id) => `/crm/account-activities/${id}`,
  editPath: (id) => `/crm/account-activities/${id}/edit`,
  columns: [
    { key: 'subject', label: 'Subject', sortable: true },
    { key: 'accountId', label: 'Account Id', sortable: true },
    { key: 'activityDate', label: 'Activity Date', sortable: true },
    { key: 'statusId', label: 'Status Lookup Id', sortable: true },
  ],
  fields: [
    { key: 'accountId', label: 'Account Id', kind: 'text', required: true },
    { key: 'contactId', label: 'Contact Id', kind: 'text' },
    { key: 'activityTypeId', label: 'Activity Type Lookup Id', kind: 'text' },
    { key: 'subject', label: 'Subject', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'activityDate', label: 'Activity Date (ISO)', kind: 'text', required: true },
    { key: 'dueDate', label: 'Due Date (ISO)', kind: 'text' },
    { key: 'priorityId', label: 'Priority Lookup Id', kind: 'text' },
    { key: 'statusId', label: 'Status Lookup Id', kind: 'text' },
    { key: 'outcomeId', label: 'Outcome Lookup Id', kind: 'text' },
    { key: 'assignedToUserId', label: 'Assigned User Id', kind: 'text' },
    { key: 'relatedEntityType', label: 'Related Entity Type', kind: 'text' },
    { key: 'relatedEntityId', label: 'Related Entity Id', kind: 'text' },
    { key: 'isPrivate', label: 'Private', kind: 'checkbox' },
    { key: 'followUpRequired', label: 'Follow Up Required', kind: 'checkbox' },
    { key: 'followUpDate', label: 'Follow Up Date (ISO)', kind: 'text' },
  ],
  defaultForm: {
    accountId: '', contactId: '', activityTypeId: '', subject: '', description: '', activityDate: '', dueDate: '', priorityId: '', statusId: '', outcomeId: '', assignedToUserId: '', relatedEntityType: '', relatedEntityId: '', isPrivate: false, followUpRequired: false, followUpDate: '',
  },
  mapItemToForm: (item) => ({
    accountId: item.accountId,
    contactId: item.contactId ?? '',
    activityTypeId: item.activityTypeId ?? '',
    subject: item.subject,
    description: item.description ?? '',
    activityDate: item.activityDate,
    dueDate: item.dueDate ?? '',
    priorityId: item.priorityId ?? '',
    statusId: item.statusId ?? '',
    outcomeId: item.outcomeId ?? '',
    assignedToUserId: item.assignedToUserId ?? '',
    relatedEntityType: item.relatedEntityType ?? '',
    relatedEntityId: item.relatedEntityId ?? '',
    isPrivate: item.isPrivate,
    followUpRequired: item.followUpRequired,
    followUpDate: item.followUpDate ?? '',
  }),
  mapCreatePayload: (form) => ({
    accountId: String(form.accountId ?? ''),
    contactId: String(form.contactId ?? '') || null,
    activityTypeId: String(form.activityTypeId ?? '') || null,
    subject: String(form.subject ?? ''),
    description: String(form.description ?? '') || null,
    activityDate: String(form.activityDate ?? '') || new Date().toISOString(),
    dueDate: String(form.dueDate ?? '') || null,
    priorityId: String(form.priorityId ?? '') || null,
    statusId: String(form.statusId ?? '') || null,
    outcomeId: String(form.outcomeId ?? '') || null,
    assignedToUserId: String(form.assignedToUserId ?? '') || null,
    relatedEntityType: String(form.relatedEntityType ?? '') || null,
    relatedEntityId: String(form.relatedEntityId ?? '') || null,
    isPrivate: Boolean(form.isPrivate),
    followUpRequired: Boolean(form.followUpRequired),
    followUpDate: String(form.followUpDate ?? '') || null,
  }),
  mapUpdatePayload: (form, item) => {
    const payload = accountActivitiesConfig.mapCreatePayload(form) as Record<string, unknown>
    return { ...payload, id: item.id }
  },
  details: (item) => [
    { label: 'Account Id', value: item.accountId },
    { label: 'Subject', value: item.subject },
    { label: 'Activity Date', value: item.activityDate },
    { label: 'Status Lookup Id', value: item.statusId ?? '' },
    { label: 'Follow Up Required', value: item.followUpRequired ? 'Yes' : 'No' },
  ],
}

export const productsConfig: EntityConfig<Product> = {
  key: 'products',
  title: 'Products',
  subtitle: 'Manage product catalog, pricing defaults, and lifecycle status.',
  endpoint: 'api/products',
  permissions: { view: 'Products.View', create: 'Products.Create', update: 'Products.Update', delete: 'Products.Delete' },
  listPath: '/sales/products',
  createPath: '/sales/products/create',
  detailsPath: (id) => `/sales/products/${id}`,
  editPath: (id) => `/sales/products/${id}/edit`,
  columns: [
    { key: 'productCode', label: 'Product #', sortable: true },
    { key: 'name', label: 'Name', sortable: true },
    { key: 'productCategoryName', label: 'Category', sortable: true },
    { key: 'productTypeName', label: 'Type', sortable: true },
    { key: 'unitOfMeasureName', label: 'UOM', sortable: true },
    { key: 'standardPrice', label: 'Price', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Inactive') },
  ],
  fields: [
    { key: 'productCode', label: 'Product Code', kind: 'text' },
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'productCategoryId', label: 'Category', kind: 'text', required: true },
    { key: 'productTypeId', label: 'Product Type', kind: 'text', required: true },
    { key: 'unitOfMeasureId', label: 'Unit Of Measure', kind: 'text', required: true },
    { key: 'productStatusId', label: 'Product Status', kind: 'text', required: true },
    { key: 'sku', label: 'SKU', kind: 'text' },
    { key: 'barcode', label: 'Barcode', kind: 'text' },
    { key: 'manufacturer', label: 'Manufacturer', kind: 'text' },
    { key: 'brand', label: 'Brand', kind: 'text' },
    { key: 'costPrice', label: 'Cost Price', kind: 'number' },
    { key: 'standardPrice', label: 'Standard Price', kind: 'number' },
    { key: 'taxRate', label: 'Tax Rate (%)', kind: 'number' },
    { key: 'weight', label: 'Weight', kind: 'number' },
    { key: 'volume', label: 'Volume', kind: 'number' },
    { key: 'isStockItem', label: 'Stock Item', kind: 'checkbox' },
    { key: 'allowDiscount', label: 'Allow Discount', kind: 'checkbox' },
    { key: 'effectiveFrom', label: 'Effective From', kind: 'text' },
    { key: 'effectiveTo', label: 'Effective To', kind: 'text' },
    { key: 'ownerUserId', label: 'Owner User', kind: 'text' },
    { key: 'ownerTeamId', label: 'Owner Team', kind: 'text' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: {
    productCode: '',
    name: '',
    description: '',
    productCategoryId: '',
    productTypeId: '',
    unitOfMeasureId: '',
    productStatusId: '',
    sku: '',
    barcode: '',
    manufacturer: '',
    brand: '',
    costPrice: 0,
    standardPrice: 0,
    taxRate: 0,
    weight: 0,
    volume: 0,
    isStockItem: true,
    allowDiscount: true,
    effectiveFrom: '',
    effectiveTo: '',
    ownerUserId: '',
    ownerTeamId: '',
    isActive: true,
  },
  mapItemToForm: (item) => ({
    productCode: item.productCode,
    name: item.name,
    description: item.description ?? '',
    productCategoryId: item.productCategoryId,
    productTypeId: item.productTypeId,
    unitOfMeasureId: item.unitOfMeasureId,
    productStatusId: item.productStatusId,
    sku: item.sku ?? '',
    barcode: item.barcode ?? '',
    manufacturer: item.manufacturer ?? '',
    brand: item.brand ?? '',
    costPrice: item.costPrice ?? 0,
    standardPrice: item.standardPrice ?? 0,
    taxRate: item.taxRate ?? 0,
    weight: item.weight ?? 0,
    volume: item.volume ?? 0,
    isStockItem: item.isStockItem,
    allowDiscount: item.allowDiscount,
    effectiveFrom: item.effectiveFrom ?? '',
    effectiveTo: item.effectiveTo ?? '',
    ownerUserId: item.ownerUserId ?? '',
    ownerTeamId: item.ownerTeamId ?? '',
    isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    productCode: String(form.productCode ?? ''),
    name: String(form.name ?? ''),
    description: String(form.description ?? '') || null,
    productCategoryId: String(form.productCategoryId ?? ''),
    productTypeId: String(form.productTypeId ?? ''),
    unitOfMeasureId: String(form.unitOfMeasureId ?? ''),
    productStatusId: String(form.productStatusId ?? ''),
    sku: String(form.sku ?? '') || null,
    barcode: String(form.barcode ?? '') || null,
    manufacturer: String(form.manufacturer ?? '') || null,
    brand: String(form.brand ?? '') || null,
    costPrice: Number(form.costPrice ?? 0),
    standardPrice: Number(form.standardPrice ?? 0),
    taxRate: Number(form.taxRate ?? 0),
    weight: Number(form.weight ?? 0),
    volume: Number(form.volume ?? 0),
    isStockItem: Boolean(form.isStockItem),
    allowDiscount: Boolean(form.allowDiscount),
    effectiveFrom: String(form.effectiveFrom ?? '') || null,
    effectiveTo: String(form.effectiveTo ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    ownerTeamId: String(form.ownerTeamId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => productsConfig.mapCreatePayload(form),
  details: (item) => [
    { label: 'Product Code', value: item.productCode },
    { label: 'Name', value: item.name },
    { label: 'Category', value: item.productCategoryName ?? '' },
    { label: 'Type', value: item.productTypeName ?? '' },
    { label: 'UOM', value: item.unitOfMeasureName ?? '' },
    { label: 'Price', value: String(item.standardPrice ?? '') },
    { label: 'Status', value: item.isActive ? 'Active' : 'Inactive' },
  ],
}

export const productCategoriesConfig: EntityConfig<ProductCategory> = {
  key: 'product-categories',
  title: 'Product Categories',
  subtitle: 'Organize products into a maintainable hierarchy.',
  endpoint: 'api/product-categories',
  permissions: { view: 'ProductCategories.View', create: 'ProductCategories.Create', update: 'ProductCategories.Update', delete: 'ProductCategories.Delete' },
  listPath: '/sales/product-categories',
  createPath: '/sales/product-categories/create',
  detailsPath: (id) => `/sales/product-categories/${id}`,
  editPath: (id) => `/sales/product-categories/${id}/edit`,
  columns: [
    { key: 'code', label: 'Code', sortable: true },
    { key: 'name', label: 'Name', sortable: true },
    { key: 'parentCategoryName', label: 'Parent', sortable: true },
    { key: 'productCount', label: 'Products', sortable: true },
    { key: 'sortOrder', label: 'Sort', sortable: true },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Inactive') },
  ],
  fields: [
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'code', label: 'Code', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'parentCategoryId', label: 'Parent Category', kind: 'text' },
    { key: 'sortOrder', label: 'Sort Order', kind: 'number' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: { name: '', code: '', description: '', parentCategoryId: '', sortOrder: 0, isActive: true },
  mapItemToForm: (item) => ({
    name: item.name,
    code: item.code,
    description: item.description ?? '',
    parentCategoryId: item.parentCategoryId ?? '',
    sortOrder: item.sortOrder,
    isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    name: String(form.name ?? ''),
    code: String(form.code ?? ''),
    description: String(form.description ?? '') || null,
    parentCategoryId: String(form.parentCategoryId ?? '') || null,
    sortOrder: Number(form.sortOrder ?? 0),
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => productCategoriesConfig.mapCreatePayload(form),
  details: (item) => [
    { label: 'Code', value: item.code },
    { label: 'Name', value: item.name },
    { label: 'Parent', value: item.parentCategoryName ?? '' },
    { label: 'Products', value: String(item.productCount) },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const priceListsConfig: EntityConfig<PriceList> = {
  key: 'price-lists',
  title: 'Price Lists',
  subtitle: 'Maintain sell prices by currency and effective period.',
  endpoint: 'api/price-lists',
  permissions: { view: 'PriceLists.View', create: 'PriceLists.Create', update: 'PriceLists.Update', delete: 'PriceLists.Delete' },
  listPath: '/sales/price-lists',
  createPath: '/sales/price-lists/create',
  detailsPath: (id) => `/sales/price-lists/${id}/items`,
  editPath: (id) => `/sales/price-lists/${id}/edit`,
  columns: [
    { key: 'priceListNumber', label: 'Price List #', sortable: true },
    { key: 'name', label: 'Name', sortable: true },
    { key: 'currencyName', label: 'Currency', sortable: true },
    { key: 'effectiveFrom', label: 'Effective From', sortable: true },
    { key: 'effectiveTo', label: 'Effective To', sortable: true },
    { key: 'isDefault', label: 'Default', sortable: true, render: (row) => statusCell(row.isDefault ? 'Default' : 'No') },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Inactive') },
  ],
  fields: [
    { key: 'priceListNumber', label: 'Price List Number', kind: 'text' },
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'currencyId', label: 'Currency', kind: 'text', required: true },
    { key: 'effectiveFrom', label: 'Effective From', kind: 'text' },
    { key: 'effectiveTo', label: 'Effective To', kind: 'text' },
    { key: 'isDefault', label: 'Default', kind: 'checkbox' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: { priceListNumber: '', name: '', description: '', currencyId: '', effectiveFrom: '', effectiveTo: '', isDefault: false, isActive: true },
  mapItemToForm: (item) => ({
    priceListNumber: item.priceListNumber,
    name: item.name,
    description: item.description ?? '',
    currencyId: item.currencyId,
    effectiveFrom: item.effectiveFrom ?? '',
    effectiveTo: item.effectiveTo ?? '',
    isDefault: item.isDefault,
    isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    priceListNumber: String(form.priceListNumber ?? ''),
    name: String(form.name ?? ''),
    description: String(form.description ?? '') || null,
    currencyId: String(form.currencyId ?? ''),
    effectiveFrom: String(form.effectiveFrom ?? '') || null,
    effectiveTo: String(form.effectiveTo ?? '') || null,
    isDefault: Boolean(form.isDefault),
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => priceListsConfig.mapCreatePayload(form),
  details: (item) => [
    { label: 'Price List Number', value: item.priceListNumber },
    { label: 'Name', value: item.name },
    { label: 'Currency', value: item.currencyName ?? '' },
    { label: 'Default', value: item.isDefault ? 'Yes' : 'No' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
  listRowActions: [
    { key: 'manage-items', label: 'Manage Items', to: (item) => `/sales/price-lists/${item.id}/items` },
  ],
}

export const priceListItemsConfig: EntityConfig<PriceListItem> = {
  key: 'price-list-items',
  title: 'Price List Items',
  subtitle: 'Maintain product line pricing entries for each price list.',
  endpoint: 'api/price-list-items',
  permissions: { view: 'PriceLists.View', create: 'PriceLists.Update', update: 'PriceLists.Update', delete: 'PriceLists.Delete' },
  listPath: '/sales/price-list-items',
  createPath: '/sales/price-list-items/create',
  detailsPath: (id) => `/sales/price-list-items/${id}`,
  editPath: (id) => `/sales/price-list-items/${id}/edit`,
  columns: [
    { key: 'productCode', label: 'Product #', sortable: true },
    { key: 'productName', label: 'Product', sortable: true },
    { key: 'unitPrice', label: 'Unit Price', sortable: true },
    { key: 'minimumQuantity', label: 'Min Qty', sortable: true },
    { key: 'maximumQuantity', label: 'Max Qty', sortable: true },
    { key: 'discountPercent', label: 'Discount %', sortable: true },
  ],
  fields: [
    { key: 'priceListId', label: 'Price List', kind: 'text', required: true },
    { key: 'productId', label: 'Product', kind: 'text', required: true },
    { key: 'unitPrice', label: 'Unit Price', kind: 'number', required: true },
    { key: 'minimumQuantity', label: 'Minimum Quantity', kind: 'number' },
    { key: 'maximumQuantity', label: 'Maximum Quantity', kind: 'number' },
    { key: 'discountPercent', label: 'Discount Percent', kind: 'number' },
    { key: 'effectiveFrom', label: 'Effective From', kind: 'text' },
    { key: 'effectiveTo', label: 'Effective To', kind: 'text' },
  ],
  defaultForm: { priceListId: '', productId: '', unitPrice: 0, minimumQuantity: 0, maximumQuantity: 0, discountPercent: 0, effectiveFrom: '', effectiveTo: '' },
  mapItemToForm: (item) => ({
    priceListId: item.priceListId,
    productId: item.productId,
    unitPrice: item.unitPrice,
    minimumQuantity: item.minimumQuantity ?? 0,
    maximumQuantity: item.maximumQuantity ?? 0,
    discountPercent: item.discountPercent ?? 0,
    effectiveFrom: item.effectiveFrom ?? '',
    effectiveTo: item.effectiveTo ?? '',
  }),
  mapCreatePayload: (form) => ({
    productId: String(form.productId ?? ''),
    unitPrice: Number(form.unitPrice ?? 0),
    minimumQuantity: Number(form.minimumQuantity ?? 0) || null,
    maximumQuantity: Number(form.maximumQuantity ?? 0) || null,
    discountPercent: Number(form.discountPercent ?? 0) || null,
    effectiveFrom: String(form.effectiveFrom ?? '') || null,
    effectiveTo: String(form.effectiveTo ?? '') || null,
  }),
  mapUpdatePayload: (form) => priceListItemsConfig.mapCreatePayload(form),
  details: (item) => [
    { label: 'Product', value: `${item.productName} (${item.productCode})` },
    { label: 'Unit Price', value: String(item.unitPrice) },
    { label: 'Min Qty', value: String(item.minimumQuantity ?? '') },
    { label: 'Max Qty', value: String(item.maximumQuantity ?? '') },
  ],
}

export const productBundlesConfig: EntityConfig<ProductBundle> = {
  key: 'product-bundles',
  title: 'Product Bundles',
  subtitle: 'Group products into bundles and control component pricing behavior.',
  endpoint: 'api/product-bundles',
  permissions: { view: 'ProductBundles.View', create: 'ProductBundles.Create', update: 'ProductBundles.Update', delete: 'ProductBundles.Delete' },
  listPath: '/sales/product-bundles',
  createPath: '/sales/product-bundles/create',
  detailsPath: (id) => `/sales/product-bundles/${id}/items`,
  editPath: (id) => `/sales/product-bundles/${id}/edit`,
  columns: [
    { key: 'bundleCode', label: 'Bundle #', sortable: true },
    { key: 'name', label: 'Name', sortable: true },
    { key: 'bundlePrice', label: 'Bundle Price', sortable: true },
    { key: 'allowComponentOverride', label: 'Component Override', sortable: true, render: (row) => statusCell(row.allowComponentOverride ? 'Allowed' : 'Locked') },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Inactive') },
  ],
  fields: [
    { key: 'bundleCode', label: 'Bundle Code', kind: 'text' },
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'bundlePrice', label: 'Bundle Price', kind: 'number' },
    { key: 'allowComponentOverride', label: 'Allow Component Override', kind: 'checkbox' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: { bundleCode: '', name: '', description: '', bundlePrice: 0, allowComponentOverride: false, isActive: true },
  mapItemToForm: (item) => ({
    bundleCode: item.bundleCode,
    name: item.name,
    description: item.description ?? '',
    bundlePrice: item.bundlePrice ?? 0,
    allowComponentOverride: item.allowComponentOverride,
    isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    bundleCode: String(form.bundleCode ?? ''),
    name: String(form.name ?? ''),
    description: String(form.description ?? '') || null,
    bundlePrice: Number(form.bundlePrice ?? 0),
    allowComponentOverride: Boolean(form.allowComponentOverride),
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => productBundlesConfig.mapCreatePayload(form),
  details: (item) => [
    { label: 'Bundle Code', value: item.bundleCode },
    { label: 'Name', value: item.name },
    { label: 'Bundle Price', value: String(item.bundlePrice ?? '') },
    { label: 'Allow Component Override', value: item.allowComponentOverride ? 'Yes' : 'No' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
  listRowActions: [
    { key: 'manage-items', label: 'Manage Items', to: (item) => `/sales/product-bundles/${item.id}/items` },
  ],
}

export const unitOfMeasuresConfig: EntityConfig<UnitOfMeasure> = {
  key: 'unit-of-measures',
  title: 'Units Of Measure',
  subtitle: 'Define sellable and stock measurement units.',
  endpoint: 'api/unit-of-measures',
  permissions: { view: 'UnitOfMeasures.View', create: 'UnitOfMeasures.Create', update: 'UnitOfMeasures.Update', delete: 'UnitOfMeasures.Delete' },
  listPath: '/sales/unit-of-measures',
  createPath: '/sales/unit-of-measures/create',
  detailsPath: (id) => `/sales/unit-of-measures/${id}`,
  editPath: (id) => `/sales/unit-of-measures/${id}/edit`,
  columns: [
    { key: 'code', label: 'Code', sortable: true },
    { key: 'name', label: 'Name', sortable: true },
    { key: 'sortOrder', label: 'Sort', sortable: true },
    { key: 'isDefault', label: 'Default', sortable: true, render: (row) => statusCell(row.isDefault ? 'Default' : 'No') },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Inactive') },
  ],
  fields: [
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'code', label: 'Code', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'sortOrder', label: 'Sort Order', kind: 'number' },
    { key: 'isDefault', label: 'Default', kind: 'checkbox' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: { name: '', code: '', description: '', sortOrder: 0, isDefault: false, isActive: true },
  mapItemToForm: (item) => ({
    name: item.name,
    code: item.code,
    description: item.description ?? '',
    sortOrder: item.sortOrder,
    isDefault: item.isDefault,
    isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    name: String(form.name ?? ''),
    code: String(form.code ?? ''),
    description: String(form.description ?? '') || null,
    sortOrder: Number(form.sortOrder ?? 0),
    isDefault: Boolean(form.isDefault),
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => unitOfMeasuresConfig.mapCreatePayload(form),
  details: (item) => [
    { label: 'Code', value: item.code },
    { label: 'Name', value: item.name },
    { label: 'Sort Order', value: String(item.sortOrder) },
    { label: 'Default', value: item.isDefault ? 'Yes' : 'No' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const discountsConfig: EntityConfig<Discount> = {
  key: 'discounts',
  title: 'Discounts',
  subtitle: 'Define standalone discount policies for products and deals.',
  endpoint: 'api/discounts',
  permissions: { view: 'Discounts.View', create: 'Discounts.Create', update: 'Discounts.Update', delete: 'Discounts.Delete' },
  listPath: '/sales/discounts',
  createPath: '/sales/discounts/create',
  detailsPath: (id) => `/sales/discounts/${id}`,
  editPath: (id) => `/sales/discounts/${id}/edit`,
  columns: [
    { key: 'code', label: 'Code', sortable: true },
    { key: 'name', label: 'Name', sortable: true },
    { key: 'discountTypeName', label: 'Type', sortable: true },
    { key: 'value', label: 'Value', sortable: true },
    { key: 'maximumAmount', label: 'Max Amount', sortable: true },
    { key: 'isStackable', label: 'Stackable', sortable: true, render: (row) => statusCell(row.isStackable ? 'Yes' : 'No') },
    { key: 'isActive', label: 'Status', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Inactive') },
  ],
  fields: [
    { key: 'name', label: 'Name', kind: 'text', required: true },
    { key: 'code', label: 'Code', kind: 'text', required: true },
    { key: 'discountTypeId', label: 'Discount Type', kind: 'text', required: true },
    { key: 'value', label: 'Value', kind: 'number', required: true },
    { key: 'maximumAmount', label: 'Maximum Amount', kind: 'number' },
    { key: 'isStackable', label: 'Stackable', kind: 'checkbox' },
    { key: 'effectiveFrom', label: 'Effective From', kind: 'text' },
    { key: 'effectiveTo', label: 'Effective To', kind: 'text' },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: {
    name: '',
    code: '',
    discountTypeId: '',
    value: 0,
    maximumAmount: 0,
    isStackable: false,
    effectiveFrom: '',
    effectiveTo: '',
    description: '',
    isActive: true,
  },
  mapItemToForm: (item) => ({
    name: item.name,
    code: item.code,
    discountTypeId: item.discountTypeId,
    value: item.value,
    maximumAmount: item.maximumAmount ?? 0,
    isStackable: item.isStackable,
    effectiveFrom: item.effectiveFrom ?? '',
    effectiveTo: item.effectiveTo ?? '',
    description: item.description ?? '',
    isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    name: String(form.name ?? ''),
    code: String(form.code ?? ''),
    discountTypeId: String(form.discountTypeId ?? ''),
    value: Number(form.value ?? 0),
    maximumAmount: Number(form.maximumAmount ?? 0),
    isStackable: Boolean(form.isStackable),
    effectiveFrom: String(form.effectiveFrom ?? '') || null,
    effectiveTo: String(form.effectiveTo ?? '') || null,
    description: String(form.description ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => discountsConfig.mapCreatePayload(form),
  details: (item) => [
    { label: 'Code', value: item.code },
    { label: 'Name', value: item.name },
    { label: 'Type', value: item.discountTypeName ?? '' },
    { label: 'Value', value: String(item.value) },
    { label: 'Max Amount', value: String(item.maximumAmount ?? '') },
    { label: 'Stackable', value: item.isStackable ? 'Yes' : 'No' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
}

export const quotesConfig: EntityConfig<Quote> = {
  key: 'quotes',
  title: 'Quotes',
  subtitle: 'Manage customer quotations, approval status, and conversion readiness.',
  endpoint: 'api/quotes',
  permissions: { view: 'Quotes.View', create: 'Quotes.Create', update: 'Quotes.Update', delete: 'Quotes.Delete' },
  listPath: '/sales/quotes',
  createPath: '/sales/quotes/create',
  detailsPath: (id) => `/sales/quotes/${id}/lines`,
  editPath: (id) => `/sales/quotes/${id}/edit`,
  columns: [
    { key: 'quoteNumber', label: 'Quote #', sortable: true },
    { key: 'accountName', label: 'Account', sortable: true },
    { key: 'quoteStatusName', label: 'Status', sortable: true },
    { key: 'approvalStatusName', label: 'Approval', sortable: true },
    { key: 'currencyName', label: 'Currency', sortable: true },
    { key: 'totalAmount', label: 'Total', sortable: true },
    { key: 'validTo', label: 'Valid To', sortable: true },
    { key: 'isActive', label: 'Active', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Inactive') },
  ],
  fields: [
    { key: 'quoteNumber', label: 'Quote Number', kind: 'text' },
    { key: 'accountId', label: 'Account', kind: 'text', required: true },
    { key: 'contactId', label: 'Contact', kind: 'text' },
    { key: 'opportunityId', label: 'Opportunity', kind: 'text' },
    { key: 'priceListId', label: 'Price List', kind: 'text', required: true },
    { key: 'currencyId', label: 'Currency', kind: 'text', required: true },
    { key: 'quoteStatusId', label: 'Quote Status', kind: 'text', required: true },
    { key: 'approvalStatusId', label: 'Approval Status', kind: 'text', required: true },
    { key: 'validFrom', label: 'Valid From', kind: 'text' },
    { key: 'validTo', label: 'Valid To', kind: 'text' },
    { key: 'notes', label: 'Notes', kind: 'textarea' },
    { key: 'termsAndConditions', label: 'Terms And Conditions', kind: 'textarea' },
    { key: 'ownerUserId', label: 'Owner User', kind: 'text' },
    { key: 'ownerTeamId', label: 'Owner Team', kind: 'text' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: {
    quoteNumber: '',
    accountId: '',
    contactId: '',
    opportunityId: '',
    priceListId: '',
    currencyId: '',
    quoteStatusId: '',
    approvalStatusId: '',
    validFrom: '',
    validTo: '',
    notes: '',
    termsAndConditions: '',
    ownerUserId: '',
    ownerTeamId: '',
    isActive: true,
  },
  mapItemToForm: (item) => ({
    quoteNumber: item.quoteNumber,
    accountId: item.accountId,
    contactId: item.contactId ?? '',
    opportunityId: item.opportunityId ?? '',
    priceListId: item.priceListId,
    currencyId: item.currencyId,
    quoteStatusId: item.quoteStatusId,
    approvalStatusId: item.approvalStatusId,
    validFrom: item.validFrom ?? '',
    validTo: item.validTo ?? '',
    notes: item.notes ?? '',
    termsAndConditions: item.termsAndConditions ?? '',
    ownerUserId: item.ownerUserId ?? '',
    ownerTeamId: item.ownerTeamId ?? '',
    isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    quoteNumber: String(form.quoteNumber ?? ''),
    accountId: String(form.accountId ?? ''),
    contactId: String(form.contactId ?? '') || null,
    opportunityId: String(form.opportunityId ?? '') || null,
    priceListId: String(form.priceListId ?? ''),
    currencyId: String(form.currencyId ?? ''),
    quoteStatusId: String(form.quoteStatusId ?? ''),
    approvalStatusId: String(form.approvalStatusId ?? ''),
    validFrom: String(form.validFrom ?? '') || null,
    validTo: String(form.validTo ?? '') || null,
    notes: String(form.notes ?? '') || null,
    termsAndConditions: String(form.termsAndConditions ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    ownerTeamId: String(form.ownerTeamId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => quotesConfig.mapCreatePayload(form),
  details: (item) => [
    { label: 'Quote Number', value: item.quoteNumber },
    { label: 'Account', value: item.accountName ?? '' },
    { label: 'Quote Status', value: item.quoteStatusName ?? '' },
    { label: 'Approval Status', value: item.approvalStatusName ?? '' },
    { label: 'Currency', value: item.currencyName ?? '' },
    { label: 'Total', value: String(item.totalAmount) },
    { label: 'Valid To', value: item.validTo ?? '' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
  listRowActions: [
    { key: 'manage-lines', label: 'Manage Lines', to: (item) => `/sales/quotes/${item.id}/lines` },
  ],
  generatedNumber: { fieldKey: 'quoteNumber', sequenceCode: 'QUOTE' },
}

export const ordersConfig: EntityConfig<Order> = {
  key: 'orders',
  title: 'Orders',
  subtitle: 'Manage customer orders and fulfillment progress.',
  endpoint: 'api/orders',
  permissions: { view: 'Orders.View', create: 'Orders.Create', update: 'Orders.Update', delete: 'Orders.Delete' },
  listPath: '/sales/orders',
  createPath: '/sales/orders/create',
  detailsPath: (id) => `/sales/orders/${id}/lines`,
  editPath: (id) => `/sales/orders/${id}/edit`,
  columns: [
    { key: 'orderNumber', label: 'Order #', sortable: true },
    { key: 'accountName', label: 'Account', sortable: true },
    { key: 'orderStatusName', label: 'Status', sortable: true },
    { key: 'approvalStatusName', label: 'Approval', sortable: true },
    { key: 'deliveryStatusName', label: 'Delivery', sortable: true },
    { key: 'billingStatusName', label: 'Billing', sortable: true },
    { key: 'currencyName', label: 'Currency', sortable: true },
    { key: 'totalAmount', label: 'Total', sortable: true },
    { key: 'isActive', label: 'Active', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Inactive') },
  ],
  fields: [
    { key: 'orderNumber', label: 'Order Number', kind: 'text' },
    { key: 'quoteId', label: 'Quote', kind: 'text' },
    { key: 'accountId', label: 'Account', kind: 'text', required: true },
    { key: 'contactId', label: 'Contact', kind: 'text' },
    { key: 'opportunityId', label: 'Opportunity', kind: 'text' },
    { key: 'currencyId', label: 'Currency', kind: 'text', required: true },
    { key: 'orderStatusId', label: 'Order Status', kind: 'text', required: true },
    { key: 'orderApprovalStatusId', label: 'Approval Status', kind: 'text', required: true },
    { key: 'deliveryStatusId', label: 'Delivery Status', kind: 'text', required: true },
    { key: 'billingStatusId', label: 'Billing Status', kind: 'text', required: true },
    { key: 'orderDate', label: 'Order Date', kind: 'text' },
    { key: 'expectedDeliveryDate', label: 'Expected Delivery Date', kind: 'text' },
    { key: 'deliveryDate', label: 'Delivery Date', kind: 'text' },
    { key: 'billingDate', label: 'Billing Date', kind: 'text' },
    { key: 'notes', label: 'Notes', kind: 'textarea' },
    { key: 'ownerUserId', label: 'Owner User', kind: 'text' },
    { key: 'ownerTeamId', label: 'Owner Team', kind: 'text' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: {
    orderNumber: '',
    quoteId: '',
    accountId: '',
    contactId: '',
    opportunityId: '',
    currencyId: '',
    orderStatusId: '',
    orderApprovalStatusId: '',
    deliveryStatusId: '',
    billingStatusId: '',
    orderDate: '',
    expectedDeliveryDate: '',
    deliveryDate: '',
    billingDate: '',
    notes: '',
    ownerUserId: '',
    ownerTeamId: '',
    isActive: true,
  },
  mapItemToForm: (item) => ({
    orderNumber: item.orderNumber,
    quoteId: item.quoteId ?? '',
    accountId: item.accountId,
    contactId: item.contactId ?? '',
    opportunityId: item.opportunityId ?? '',
    currencyId: item.currencyId,
    orderStatusId: item.orderStatusId,
    orderApprovalStatusId: item.approvalStatusId,
    deliveryStatusId: item.deliveryStatusId,
    billingStatusId: item.billingStatusId,
    orderDate: item.orderDate ?? '',
    expectedDeliveryDate: item.expectedDeliveryDate ?? '',
    deliveryDate: item.deliveryDate ?? '',
    billingDate: item.billingDate ?? '',
    notes: item.notes ?? '',
    ownerUserId: item.ownerUserId ?? '',
    ownerTeamId: item.ownerTeamId ?? '',
    isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    orderNumber: String(form.orderNumber ?? ''),
    quoteId: String(form.quoteId ?? '') || null,
    accountId: String(form.accountId ?? ''),
    contactId: String(form.contactId ?? '') || null,
    opportunityId: String(form.opportunityId ?? '') || null,
    currencyId: String(form.currencyId ?? ''),
    orderStatusId: String(form.orderStatusId ?? ''),
    approvalStatusId: String(form.orderApprovalStatusId ?? ''),
    deliveryStatusId: String(form.deliveryStatusId ?? ''),
    billingStatusId: String(form.billingStatusId ?? ''),
    orderDate: String(form.orderDate ?? '') || null,
    expectedDeliveryDate: String(form.expectedDeliveryDate ?? '') || null,
    deliveryDate: String(form.deliveryDate ?? '') || null,
    billingDate: String(form.billingDate ?? '') || null,
    notes: String(form.notes ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    ownerTeamId: String(form.ownerTeamId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => ordersConfig.mapCreatePayload(form),
  details: (item) => [
    { label: 'Order Number', value: item.orderNumber },
    { label: 'Account', value: item.accountName ?? '' },
    { label: 'Order Status', value: item.orderStatusName ?? '' },
    { label: 'Approval Status', value: item.approvalStatusName ?? '' },
    { label: 'Delivery Status', value: item.deliveryStatusName ?? '' },
    { label: 'Billing Status', value: item.billingStatusName ?? '' },
    { label: 'Currency', value: item.currencyName ?? '' },
    { label: 'Total', value: String(item.totalAmount) },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
  listRowActions: [
    { key: 'manage-lines', label: 'Manage Lines', to: (item) => `/sales/orders/${item.id}/lines` },
  ],
  generatedNumber: { fieldKey: 'orderNumber', sequenceCode: 'ORDER' },
}

export const invoicesConfig: EntityConfig<Invoice> = {
  key: 'invoices',
  title: 'Invoices',
  subtitle: 'Manage customer invoices and payment status progression.',
  endpoint: 'api/invoices',
  permissions: { view: 'Invoices.View', create: 'Invoices.Create', update: 'Invoices.Update', delete: 'Invoices.Delete' },
  listPath: '/sales/invoices',
  createPath: '/sales/invoices/create',
  detailsPath: (id) => `/sales/invoices/${id}/lines`,
  editPath: (id) => `/sales/invoices/${id}/edit`,
  columns: [
    { key: 'invoiceNumber', label: 'Invoice #', sortable: true },
    { key: 'accountName', label: 'Account', sortable: true },
    { key: 'invoiceStatusName', label: 'Status', sortable: true },
    { key: 'paymentStatusName', label: 'Payment', sortable: true },
    { key: 'currencyName', label: 'Currency', sortable: true },
    { key: 'totalAmount', label: 'Total', sortable: true },
    { key: 'paidAmount', label: 'Paid', sortable: true },
    { key: 'dueDate', label: 'Due Date', sortable: true },
    { key: 'isActive', label: 'Active', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Inactive') },
  ],
  fields: [
    { key: 'invoiceNumber', label: 'Invoice Number', kind: 'text' },
    { key: 'orderId', label: 'Order', kind: 'text' },
    { key: 'quoteId', label: 'Quote', kind: 'text' },
    { key: 'accountId', label: 'Account', kind: 'text', required: true },
    { key: 'contactId', label: 'Contact', kind: 'text' },
    { key: 'opportunityId', label: 'Opportunity', kind: 'text' },
    { key: 'currencyId', label: 'Currency', kind: 'text', required: true },
    { key: 'invoiceStatusId', label: 'Invoice Status', kind: 'text', required: true },
    { key: 'paymentStatusId', label: 'Payment Status', kind: 'text', required: true },
    { key: 'invoiceDate', label: 'Invoice Date', kind: 'text' },
    { key: 'dueDate', label: 'Due Date', kind: 'text' },
    { key: 'paidDate', label: 'Paid Date', kind: 'text' },
    { key: 'paidAmount', label: 'Paid Amount', kind: 'number' },
    { key: 'notes', label: 'Notes', kind: 'textarea' },
    { key: 'ownerUserId', label: 'Owner User', kind: 'text' },
    { key: 'ownerTeamId', label: 'Owner Team', kind: 'text' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: {
    invoiceNumber: '',
    orderId: '',
    quoteId: '',
    accountId: '',
    contactId: '',
    opportunityId: '',
    currencyId: '',
    invoiceStatusId: '',
    paymentStatusId: '',
    invoiceDate: '',
    dueDate: '',
    paidDate: '',
    paidAmount: 0,
    notes: '',
    ownerUserId: '',
    ownerTeamId: '',
    isActive: true,
  },
  mapItemToForm: (item) => ({
    invoiceNumber: item.invoiceNumber,
    orderId: item.orderId ?? '',
    quoteId: item.quoteId ?? '',
    accountId: item.accountId,
    contactId: item.contactId ?? '',
    opportunityId: item.opportunityId ?? '',
    currencyId: item.currencyId,
    invoiceStatusId: item.invoiceStatusId,
    paymentStatusId: item.paymentStatusId,
    invoiceDate: item.invoiceDate ?? '',
    dueDate: item.dueDate ?? '',
    paidDate: item.paidDate ?? '',
    paidAmount: item.paidAmount,
    notes: item.notes ?? '',
    ownerUserId: item.ownerUserId ?? '',
    ownerTeamId: item.ownerTeamId ?? '',
    isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    invoiceNumber: String(form.invoiceNumber ?? ''),
    orderId: String(form.orderId ?? '') || null,
    quoteId: String(form.quoteId ?? '') || null,
    accountId: String(form.accountId ?? ''),
    contactId: String(form.contactId ?? '') || null,
    opportunityId: String(form.opportunityId ?? '') || null,
    currencyId: String(form.currencyId ?? ''),
    invoiceStatusId: String(form.invoiceStatusId ?? ''),
    paymentStatusId: String(form.paymentStatusId ?? ''),
    invoiceDate: String(form.invoiceDate ?? '') || null,
    dueDate: String(form.dueDate ?? '') || null,
    paidDate: String(form.paidDate ?? '') || null,
    paidAmount: Number(form.paidAmount ?? 0),
    notes: String(form.notes ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    ownerTeamId: String(form.ownerTeamId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => invoicesConfig.mapCreatePayload(form),
  details: (item) => [
    { label: 'Invoice Number', value: item.invoiceNumber },
    { label: 'Account', value: item.accountName ?? '' },
    { label: 'Invoice Status', value: item.invoiceStatusName ?? '' },
    { label: 'Payment Status', value: item.paymentStatusName ?? '' },
    { label: 'Currency', value: item.currencyName ?? '' },
    { label: 'Total', value: String(item.totalAmount) },
    { label: 'Paid', value: String(item.paidAmount) },
    { label: 'Due Date', value: item.dueDate ?? '' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
  listRowActions: [
    { key: 'manage-lines', label: 'Manage Lines', to: (item) => `/sales/invoices/${item.id}/lines` },
  ],
  generatedNumber: { fieldKey: 'invoiceNumber', sequenceCode: 'INVOICE' },
}

export const casesConfig: EntityConfig<Case> = {
  key: 'cases',
  title: 'Cases',
  subtitle: 'Manage customer service cases, ownership, and lifecycle transitions.',
  endpoint: 'api/cases',
  permissions: { view: 'Cases.View', create: 'Cases.Create', update: 'Cases.Update', delete: 'Cases.Delete' },
  listPath: '/service/cases',
  createPath: '/service/cases/create',
  detailsPath: (id) => `/service/cases/${id}/comments`,
  editPath: (id) => `/service/cases/${id}/edit`,
  columns: [
    { key: 'caseNumber', label: 'Case #', sortable: true },
    { key: 'subject', label: 'Subject', sortable: true },
    { key: 'accountName', label: 'Account', sortable: true },
    { key: 'caseStatusName', label: 'Status', sortable: true },
    { key: 'priorityName', label: 'Priority', sortable: true },
    { key: 'assignedToUserName', label: 'Assigned To', sortable: true },
    { key: 'dueAt', label: 'Due', sortable: true },
    { key: 'isActive', label: 'Active', sortable: true, render: (row) => statusCell(row.isActive ? 'Active' : 'Inactive') },
  ],
  fields: [
    { key: 'caseNumber', label: 'Case Number', kind: 'text' },
    { key: 'accountId', label: 'Account', kind: 'text', required: true },
    { key: 'contactId', label: 'Contact', kind: 'text' },
    { key: 'opportunityId', label: 'Opportunity', kind: 'text' },
    { key: 'subject', label: 'Subject', kind: 'text', required: true },
    { key: 'description', label: 'Description', kind: 'textarea' },
    { key: 'caseStatusId', label: 'Case Status', kind: 'text', required: true },
    { key: 'casePriorityId', label: 'Priority', kind: 'text', required: true },
    { key: 'severityId', label: 'Severity', kind: 'text' },
    { key: 'categoryId', label: 'Category', kind: 'text' },
    { key: 'sourceId', label: 'Source', kind: 'text' },
    { key: 'assignedToUserId', label: 'Assigned To', kind: 'text' },
    { key: 'escalatedToUserId', label: 'Escalated To', kind: 'text' },
    { key: 'openedAt', label: 'Opened At', kind: 'text' },
    { key: 'dueAt', label: 'Due At', kind: 'text' },
    { key: 'resolvedAt', label: 'Resolved At', kind: 'text' },
    { key: 'closedAt', label: 'Closed At', kind: 'text' },
    { key: 'resolutionSummary', label: 'Resolution Summary', kind: 'textarea' },
    { key: 'ownerUserId', label: 'Owner User', kind: 'text' },
    { key: 'ownerTeamId', label: 'Owner Team', kind: 'text' },
    { key: 'isActive', label: 'Active', kind: 'checkbox' },
  ],
  defaultForm: {
    caseNumber: '',
    accountId: '',
    contactId: '',
    opportunityId: '',
    subject: '',
    description: '',
    caseStatusId: '',
    casePriorityId: '',
    severityId: '',
    categoryId: '',
    sourceId: '',
    assignedToUserId: '',
    escalatedToUserId: '',
    openedAt: '',
    dueAt: '',
    resolvedAt: '',
    closedAt: '',
    resolutionSummary: '',
    ownerUserId: '',
    ownerTeamId: '',
    isActive: true,
  },
  mapItemToForm: (item) => ({
    caseNumber: item.caseNumber,
    accountId: item.accountId,
    contactId: item.contactId ?? '',
    opportunityId: item.opportunityId ?? '',
    subject: item.subject,
    description: item.description ?? '',
    caseStatusId: item.caseStatusId,
    casePriorityId: item.priorityId,
    severityId: item.severityId ?? '',
    categoryId: item.categoryId ?? '',
    sourceId: item.sourceId ?? '',
    assignedToUserId: item.assignedToUserId ?? '',
    escalatedToUserId: item.escalatedToUserId ?? '',
    openedAt: item.openedAt ?? '',
    dueAt: item.dueAt ?? '',
    resolvedAt: item.resolvedAt ?? '',
    closedAt: item.closedAt ?? '',
    resolutionSummary: item.resolutionSummary ?? '',
    ownerUserId: item.ownerUserId ?? '',
    ownerTeamId: item.ownerTeamId ?? '',
    isActive: item.isActive,
  }),
  mapCreatePayload: (form) => ({
    caseNumber: String(form.caseNumber ?? ''),
    accountId: String(form.accountId ?? ''),
    contactId: String(form.contactId ?? '') || null,
    opportunityId: String(form.opportunityId ?? '') || null,
    subject: String(form.subject ?? ''),
    description: String(form.description ?? '') || null,
    caseStatusId: String(form.caseStatusId ?? ''),
    priorityId: String(form.casePriorityId ?? ''),
    severityId: String(form.severityId ?? '') || null,
    categoryId: String(form.categoryId ?? '') || null,
    sourceId: String(form.sourceId ?? '') || null,
    assignedToUserId: String(form.assignedToUserId ?? '') || null,
    escalatedToUserId: String(form.escalatedToUserId ?? '') || null,
    openedAt: String(form.openedAt ?? '') || null,
    dueAt: String(form.dueAt ?? '') || null,
    resolvedAt: String(form.resolvedAt ?? '') || null,
    closedAt: String(form.closedAt ?? '') || null,
    resolutionSummary: String(form.resolutionSummary ?? '') || null,
    ownerUserId: String(form.ownerUserId ?? '') || null,
    ownerTeamId: String(form.ownerTeamId ?? '') || null,
    isActive: Boolean(form.isActive),
  }),
  mapUpdatePayload: (form) => casesConfig.mapCreatePayload(form),
  details: (item) => [
    { label: 'Case Number', value: item.caseNumber },
    { label: 'Subject', value: item.subject },
    { label: 'Account', value: item.accountName ?? '' },
    { label: 'Case Status', value: item.caseStatusName ?? '' },
    { label: 'Priority', value: item.priorityName ?? '' },
    { label: 'Opened At', value: item.openedAt ?? '' },
    { label: 'Due At', value: item.dueAt ?? '' },
    { label: 'Resolved At', value: item.resolvedAt ?? '' },
    { label: 'Closed At', value: item.closedAt ?? '' },
    { label: 'Resolution Summary', value: item.resolutionSummary ?? '' },
    { label: 'Active', value: item.isActive ? 'Yes' : 'No' },
  ],
  listRowActions: [
    { key: 'manage-comments', label: 'Manage Comments', to: (item) => `/service/cases/${item.id}/comments` },
  ],
  generatedNumber: { fieldKey: 'caseNumber', sequenceCode: 'CASE' },
}

export const caseCommentsConfig: EntityConfig<CaseComment> = {
  key: 'case-comments',
  title: 'Case Comments',
  subtitle: 'Maintain case comments and internal notes.',
  endpoint: 'api/cases/comments',
  permissions: { view: 'CaseComments.View', create: 'CaseComments.Create', update: 'CaseComments.Create', delete: 'CaseComments.Delete' },
  listPath: '/service/cases',
  createPath: '/service/cases',
  detailsPath: (id) => `/service/cases/comments/${id}`,
  editPath: (id) => `/service/cases/comments/${id}`,
  columns: [
    { key: 'commentText', label: 'Comment', sortable: true },
    { key: 'isInternal', label: 'Internal', sortable: true, render: (row) => statusCell(row.isInternal ? 'Yes' : 'No') },
    { key: 'createdByName', label: 'Created By', sortable: true },
    { key: 'createdAt', label: 'Created At', sortable: true },
  ],
  fields: [],
  defaultForm: {},
  mapItemToForm: () => ({}),
  mapCreatePayload: () => ({}),
  mapUpdatePayload: () => ({}),
  details: () => [],
  readOnly: true,
}
